<?php
/**
*
* File: _admin/_inc/food/_liquibase/food/categories_main.php
* Version 1.0.0
* Date 15:43 18.10.2020
* Copyright (c) 2020 Sindre Andre Ditlefsen
* License: http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/
/*- Access check ----------------------------------------------------------------------- */
if(!(isset($define_access_to_control_panel))){
	echo"<h1>Server error 403</h1>";
	die;
}

/*- Tables ---------------------------------------------------------------------------- */

$result = mysqli_query($link, "DROP TABLE IF EXISTS $t_food_categories_main") or die(mysqli_error($link)); 


echo"


	<!-- food_categories_main -->
	";

	
	$query = "SELECT * FROM $t_food_categories_main";
	$result = mysqli_query($link, $query);
	if($result !== FALSE){
		// Count rows
		$row_cnt = mysqli_num_rows($result);
		echo"
		<p>$t_food_categories: $row_cnt</p>
		";
	}
	else{
		mysqli_query($link, "CREATE TABLE $t_food_categories_main(
	  	 main_category_id INT NOT NULL AUTO_INCREMENT,
	 	  PRIMARY KEY(main_category_id), 
	  	   main_category_name VARCHAR(50),
	  	   main_category_icon_path VARCHAR(50),
	  	   main_category_icon_inactive_32x32 VARCHAR(50),
	  	   main_category_icon_active_32x32 VARCHAR(50),
	  	   main_category_icon_inactive_48x48 VARCHAR(50),
	  	   main_category_icon_active_48x48 VARCHAR(50),
	  	   main_category_age_limit INT,
	  	   main_category_updated_by_user_id INT,
	  	   main_category_updated DATETIME,
	  	   main_category_note VARCHAR(50))")
		   or print(mysqli_error());



$categories = array(
  array('category_id' => '1','category_user_id' => '0','category_name' => 'Bread and cereal','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'bread_and_cereal_inactive_32x32.png','category_icon_active_32x32' => 'bread_and_cereal_active_32x32.png','category_icon_inactive_48x48' => 'bread_and_cereal_inactive_48x48.png','category_icon_active_48x48' => 'bread_and_cereal_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '2','category_user_id' => '0','category_name' => 'Bread','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => 'bread_inactive_48x48.png','category_icon_active_48x48' => 'bread_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '3','category_user_id' => '0','category_name' => 'Cereals','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '4','category_user_id' => '0','category_name' => 'Frozen bread and rolls','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '5','category_user_id' => '0','category_name' => 'Crispbread','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '6','category_user_id' => '0','category_name' => 'Hotdog buns','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '7','category_user_id' => '0','category_name' => 'Dessert and baking','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'dessert_and_baking_inactive_32x32.png','category_icon_active_32x32' => 'dessert_and_baking_active_32x32.png','category_icon_inactive_48x48' => 'dessert_and_baking_inactive_48x48.png','category_icon_active_48x48' => 'dessert_and_baking_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '8','category_user_id' => '0','category_name' => 'Baking Mix','category_age_restriction' => '0','category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '9','category_user_id' => '0','category_name' => 'Biscuit','category_age_restriction' => '0','category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '10','category_user_id' => '0','category_name' => 'Cakes','category_age_restriction' => '0','category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '11','category_user_id' => '0','category_name' => 'Buns','category_age_restriction' => '0','category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '12','category_user_id' => '0','category_name' => 'Individual ice cream','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '13','category_user_id' => '0','category_name' => 'Drink','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'drink_inactive_32x32.png','category_icon_active_32x32' => 'drink_active_32x32.png','category_icon_inactive_48x48' => 'drink_inactive_48x48.png','category_icon_active_48x48' => 'drink_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '14','category_user_id' => '0','category_name' => 'Soda','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '15','category_user_id' => '0','category_name' => 'Water and mineral water','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '16','category_user_id' => '0','category_name' => 'Juice','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '17','category_user_id' => '0','category_name' => 'Smoothie','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '18','category_user_id' => '0','category_name' => 'Lemonade','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '19','category_user_id' => '0','category_name' => 'Coffee, tea and cocoa','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '20','category_user_id' => '0','category_name' => 'Energy drink','category_age_restriction' => '0','category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '21','category_user_id' => '0','category_name' => 'Fruits and vegetables','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'fruits_and_vegetables_inactive_32x32.png','category_icon_active_32x32' => 'fruits_and_vegetables_active_32x32.png','category_icon_inactive_48x48' => 'fruits_and_vegetables_inactive_48x48.png','category_icon_active_48x48' => 'fruits_and_vegetables_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '22','category_user_id' => '0','category_name' => 'Frozen vegetables','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '23','category_user_id' => '0','category_name' => 'Fruit','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '24','category_user_id' => '0','category_name' => 'Vegetables','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '25','category_user_id' => '0','category_name' => 'Canned fruits and vegetables','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '26','category_user_id' => '0','category_name' => 'Ready-made salads','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '27','category_user_id' => '0','category_name' => 'Health','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'health_inactive_32x32.png','category_icon_active_32x32' => 'health_active_32x32.png','category_icon_inactive_48x48' => 'health_inactive_48x48.png','category_icon_active_48x48' => 'health_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '28','category_user_id' => '0','category_name' => 'Protein bars','category_age_restriction' => '0','category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '29','category_user_id' => '0','category_name' => 'Protein powder','category_age_restriction' => '0','category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '30','category_user_id' => '0','category_name' => 'Meal substitutes','category_age_restriction' => '0','category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '31','category_user_id' => '0','category_name' => 'Other health products','category_age_restriction' => '0','category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '32','category_user_id' => '0','category_name' => 'Dinner','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'dinner_inactive_32x32.png','category_icon_active_32x32' => 'dinner_active_32x32.png','category_icon_inactive_48x48' => 'dinner_inactive_48x48.png','category_icon_active_48x48' => 'dinner_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '33','category_user_id' => '0','category_name' => 'Beef','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '34','category_user_id' => '0','category_name' => 'Pork and bacon','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '35','category_user_id' => '0','category_name' => 'Chicken, turkey, and duck','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '36','category_user_id' => '0','category_name' => 'Meatless','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '37','category_user_id' => '0','category_name' => 'Seafood','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '38','category_user_id' => '0','category_name' => 'Ready meals','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '39','category_user_id' => '0','category_name' => 'Pizza','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '40','category_user_id' => '0','category_name' => 'Pasta and noodle','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '41','category_user_id' => '0','category_name' => 'Taco Sauce','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '42','category_user_id' => '0','category_name' => 'Soups','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '43','category_user_id' => '0','category_name' => 'Sauces','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '44','category_user_id' => '0','category_name' => 'Dairy, cheese and eggs','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'dairy__cheese_and_eggs_inactive_32x32.png','category_icon_active_32x32' => 'dairy__cheese_and_eggs_active_32x32.png','category_icon_inactive_48x48' => 'dairy__cheese_and_eggs_inactive_48x48.png','category_icon_active_48x48' => 'dairy__cheese_and_eggs_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '45','category_user_id' => '0','category_name' => 'Eggs and Egg Substitutes','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '46','category_user_id' => '0','category_name' => 'Cream and sour cream','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '47','category_user_id' => '0','category_name' => 'Yogurt','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '48','category_user_id' => '0','category_name' => 'Milk and Plant-Based Milk','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '49','category_user_id' => '0','category_name' => 'Butter and margarine','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '50','category_user_id' => '0','category_name' => 'Cheese','category_age_restriction' => '0','category_parent_id' => '44','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '51','category_user_id' => '0','category_name' => 'Sandwich toppings','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'sandwich_toppings_inactive_32x32.png','category_icon_active_32x32' => 'sandwich_toppings_active_32x32.png','category_icon_inactive_48x48' => 'sandwich_toppings_inactive_48x48.png','category_icon_active_48x48' => 'sandwich_toppings_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '52','category_user_id' => '0','category_name' => 'Meat and chicken toppings','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '53','category_user_id' => '0','category_name' => 'Bacon and salami','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '54','category_user_id' => '0','category_name' => 'Liver','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '55','category_user_id' => '0','category_name' => 'Salad toppings','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '56','category_user_id' => '0','category_name' => 'Fish spread','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '57','category_user_id' => '0','category_name' => 'Spreads, Jelly &amp; Honey','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '58','category_user_id' => '0','category_name' => 'Mayonnaise','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '59','category_user_id' => '0','category_name' => 'Tube spread','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '60','category_user_id' => '0','category_name' => 'Cheese for sandwich','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '61','category_user_id' => '0','category_name' => 'Other toppings','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '62','category_user_id' => '0','category_name' => 'Jam','category_age_restriction' => '0','category_parent_id' => '51','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '63','category_user_id' => '0','category_name' => 'Snacks','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'snacks_inactive_32x32.png','category_icon_active_32x32' => 'snacks_active_32x32.png','category_icon_inactive_48x48' => 'snacks_inactive_48x48.png','category_icon_active_48x48' => 'snacks_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '64','category_user_id' => '0','category_name' => 'Nuts','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '65','category_user_id' => '0','category_name' => 'Potato chips','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '66','category_user_id' => '0','category_name' => 'Chocolate','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '67','category_user_id' => '0','category_name' => 'Sweets','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '68','category_user_id' => '0','category_name' => 'Other snacks','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '69','category_user_id' => '0','category_name' => 'Fries','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '70','category_user_id' => '0','category_name' => 'Ice cream','category_age_restriction' => '0','category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '71','category_user_id' => '0','category_name' => 'Tortillas','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '72','category_user_id' => '0','category_name' => 'Taco spices','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '73','category_user_id' => '0','category_name' => 'Frozen fruit','category_age_restriction' => '0','category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '74','category_user_id' => '0','category_name' => 'Sides','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '75','category_user_id' => '0','category_name' => 'Oil and spices','category_age_restriction' => '0','category_parent_id' => '0','category_symbolic_link_to_category_id' => '0','category_icon_path' => '_uploads/food/categories','category_icon_inactive_32x32' => 'oil_and_spices_inactive_32x32.png','category_icon_active_32x32' => 'oil_and_spices_active_32x32.png','category_icon_inactive_48x48' => 'oil_and_spices_inactive_48x48.png','category_icon_active_48x48' => 'oil_and_spices_active_48x48.png','category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '76','category_user_id' => '0','category_name' => 'Ketchup and mustard','category_age_restriction' => '0','category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '77','category_user_id' => '0','category_name' => 'Cooking Oils and sprays','category_age_restriction' => '0','category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '78','category_user_id' => '0','category_name' => 'Dressing','category_age_restriction' => '0','category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '79','category_user_id' => '0','category_name' => 'Spices','category_age_restriction' => '0','category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '80','category_user_id' => '0','category_name' => 'Broth and fund','category_age_restriction' => '0','category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '81','category_user_id' => '0','category_name' => 'Protein pudding','category_age_restriction' => '0','category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '82','category_user_id' => '0','category_name' => 'Fresh baked goods','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '83','category_user_id' => '0','category_name' => 'Half-baked bread and baguettes','category_age_restriction' => '0','category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '84','category_user_id' => '0','category_name' => 'Lamb and sheep','category_age_restriction' => '0','category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '85','category_user_id' => '0','category_name' => 'Sugar &amp; Sweeteners','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '86','category_user_id' => '0','category_name' => 'Flours','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '87','category_user_id' => '0','category_name' => 'Frosting &amp; Decorations','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '88','category_user_id' => '0','category_name' => 'Cooking Wine &amp; Vinegar','category_age_restriction' => NULL,'category_parent_id' => '75','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '89','category_user_id' => '0','category_name' => 'Extracts &amp; Flavorings','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '90','category_user_id' => '0','category_name' => 'Pudding &amp; Gelatin','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '91','category_user_id' => '0','category_name' => 'Baking Chocolate','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '92','category_user_id' => '0','category_name' => 'Condiments','category_age_restriction' => NULL,'category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '93','category_user_id' => '0','category_name' => 'Miscellaneous','category_age_restriction' => NULL,'category_parent_id' => '7','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '94','category_user_id' => '0','category_name' => 'Miscellaneous','category_age_restriction' => NULL,'category_parent_id' => '1','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '95','category_user_id' => '0','category_name' => 'Tortillas','category_age_restriction' => NULL,'category_parent_id' => '1','category_symbolic_link_to_category_id' => '71','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '96','category_user_id' => '0','category_name' => 'Miscellaneous','category_age_restriction' => NULL,'category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '98','category_user_id' => '0','category_name' => 'Dried fruit','category_age_restriction' => NULL,'category_parent_id' => '21','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '99','category_user_id' => '0','category_name' => 'Pizza sauce','category_age_restriction' => NULL,'category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '100','category_user_id' => '0','category_name' => 'Pizza dough','category_age_restriction' => NULL,'category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '101','category_user_id' => '0','category_name' => 'Beer','category_age_restriction' => NULL,'category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '1'),
  array('category_id' => '102','category_user_id' => '0','category_name' => 'White wine','category_age_restriction' => NULL,'category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '1'),
  array('category_id' => '103','category_user_id' => '0','category_name' => 'Red wine','category_age_restriction' => NULL,'category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '1'),
  array('category_id' => '104','category_user_id' => '0','category_name' => 'Ice cream toppings','category_age_restriction' => NULL,'category_parent_id' => '63','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '105','category_user_id' => '0','category_name' => 'Protein Shakes','category_age_restriction' => NULL,'category_parent_id' => '27','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '0'),
  array('category_id' => '106','category_user_id' => '0','category_name' => 'Liquor','category_age_restriction' => NULL,'category_parent_id' => '13','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => NULL,'category_age_limit' => '1'),
  array('category_id' => '107','category_user_id' => '0','category_name' => 'Rice','category_age_restriction' => NULL,'category_parent_id' => '32','category_symbolic_link_to_category_id' => '0','category_icon_path' => NULL,'category_icon_inactive_32x32' => NULL,'category_icon_active_32x32' => NULL,'category_icon_inactive_48x48' => NULL,'category_icon_active_48x48' => NULL,'category_last_updated' => NULL,'category_note' => 'Created 2022-04-07 15:34:36','category_age_limit' => '0')
);

		// Loop over array
		foreach ($categories as $array) {
			$category_id_mysql = quote_smart($link, $array['category_id']);
			$category_user_id_mysql = quote_smart($link, $array['category_user_id']);
			$category_name_mysql = quote_smart($link, $array['category_name']);
			$category_age_restriction_mysql = quote_smart($link, $array['category_age_restriction']);
			$category_parent_id_mysql = quote_smart($link, $array['category_parent_id']);
			$category_symbolic_link_to_category_id_mysql = quote_smart($link, $array['category_symbolic_link_to_category_id']);

			$category_icon_path_mysql = quote_smart($link, $array['category_icon_path']);

			$category_icon_inactive_32x32_mysql = quote_smart($link, $array['category_icon_inactive_32x32']);
			$category_icon_active_32x32_mysql = quote_smart($link, $array['category_icon_active_32x32']);

			$category_icon_inactive_48x48_mysql = quote_smart($link, $array['category_icon_inactive_48x48']);
			$category_icon_active_48x48_mysql = quote_smart($link, $array['category_icon_active_48x48']);

			$category_age_limit = trim($array['category_age_limit']);
			if($category_age_limit == ""){
				$category_age_limit = "0";
			}
			$category_age_limit_mysql = quote_smart($link, $category_age_limit);

			if($array['category_parent_id'] == "0"){
				mysqli_query($link, "INSERT INTO $t_food_categories_main 
						(main_category_id, main_category_name, 
						main_category_icon_path, main_category_icon_inactive_32x32, main_category_icon_active_32x32, main_category_icon_inactive_48x48, main_category_icon_active_48x48, 
						main_category_note, main_category_age_limit) 
						VALUES
						($category_id_mysql, $category_name_mysql, 
						$category_icon_path_mysql, $category_icon_inactive_32x32_mysql, $category_icon_active_32x32_mysql, $category_icon_inactive_48x48_mysql, $category_icon_active_48x48_mysql, 
						'', $category_age_limit_mysql)")
						or die(mysqli_error($link));
			}
			else{
				mysqli_query($link, "INSERT INTO $t_food_categories_main 
						(main_category_id, main_category_name) 
						VALUES
						($category_id_mysql, 'Delete me')")
						or die(mysqli_error($link));
			}

			mysqli_query($link, "DELETE FROM $t_food_categories_main WHERE main_category_name='Delete me'") or die(mysqli_error($link));
		} // foreach

	} // exists
	echo"
	<!-- //food_categories -->

";
?>