<?php
/**
*
* File: _admin/_inc/exercises/_liquibase/equipments.php
* Version 1.0.0
* Date 12:57 24.03.2021
* Copyright (c) 2021 Sindre Andre Ditlefsen
* License: http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/
/*- Access check ----------------------------------------------------------------------- */
if(!(isset($define_access_to_control_panel))){
	echo"<h1>Server error 403</h1>";
	die;
}

/*- Tables ---------------------------------------------------------------------------- */

$result = mysqli_query($link, "DROP TABLE IF EXISTS $t_exercise_equipments") or die(mysqli_error($link)); 


echo"

	<!-- equipments -->
	";
	$query = "SELECT * FROM $t_exercise_equipments";
	$result = mysqli_query($link, $query);
	if($result !== FALSE){
		// Count rows
		$row_cnt = mysqli_num_rows($result);
		echo"
		<p>$t_exercise_equipments: $row_cnt</p>
		";
	}
	else{

		mysqli_query($link, "CREATE TABLE $t_exercise_equipments(
	  	 equipment_id INT NOT NULL AUTO_INCREMENT,
	 	  PRIMARY KEY(equipment_id), 
	  	   equipment_title VARCHAR(250), 
	  	   equipment_title_clean VARCHAR(250), 
	  	   equipment_user_id INT,
	  	   equipment_language VARCHAR(20),
	  	   equipment_muscle_group_id_main INT,
	  	   equipment_muscle_group_id_sub INT,
	  	   equipment_muscle_part_of_id INT,
	  	   equipment_type_id INT,
	  	   equipment_text TEXT,
	  	   equipment_image_path VARCHAR(250),
	  	   equipment_image_file VARCHAR(250),
	  	   equipment_created_datetime DATETIME,
	  	   equipment_updated_datetime DATETIME,
	  	   equipment_user_ip VARCHAR(250),
	  	   equipment_uniqe_hits INT,
	  	   equipment_uniqe_hits_ip_block TEXT,
	  	   equipment_likes INT,
	  	   equipment_dislikes INT,
	  	   equipment_rating INT,
	  	   equipment_rating_ip_block TEXT,
	  	   equipment_number_of_comments INT,
	  	   equipment_reported INT,
	  	   equipment_reported_checked INT,
	  	   equipment_reported_reason TEXT)")
		   or die(mysqli_error());
	
		$stram_exercise_equipments = array(
  array('equipment_id' => '1','equipment_title' => 'EZ vektstang','equipment_title_clean' => 'ez_vektstang','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '1','equipment_muscle_group_id_sub' => '2','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '<p><span lang="no" xml:lang="no"><span>EZ stangen ble oppfunnet av Lewis G. Dymeck. Den benyttes mye til bicepscurl, stÃ¥ende roing og triceps. </span></span></p>
<p><span lang="no" xml:lang="no">Den buede profilen til stangen i grepomrÃ¥det tillater brukerens hÃ¥ndledd og underarmer Ã¥ ta en mer nÃ¸ytral og naturlig stilling. Dette reduserer risikoen for skader ved Ã¸velsene. Det negative ved Ã¥ benytte EZ bar til bicepscurl er at man ikke fÃ¥r en fullstendig sammentrekning av biceps, og dermed kan det vise seg en mindre effektiv treningen.<br /></span></p>','equipment_image_path' => '_uploads/exercises/no/equipment/ez_vektstang','equipment_image_file' => 'ez_vektstang_1.png','equipment_created_datetime' => '2018-02-18 12:32:38','equipment_updated_datetime' => '2018-02-18 12:32:38','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '2','equipment_title' => 'Hantler','equipment_title_clean' => 'hantler','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '1','equipment_muscle_group_id_sub' => '2','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '<p><span lang="no" xml:lang="no"><span title="The forerunner of the dumbbell, halteres, were used in ancient Greece as lifting weights[1][2] and also as weights in the ancient Greek version of the long jump.[3]">Hantler kan spores tilbake til det gamle Hellas. Det ble der benyttet til veklÃ¸fting. Hantler er veldig mye brukt innenfor trening da de lar oss trene alt fra armer, rygg til bein. </span></span></p>','equipment_image_path' => '_uploads/exercises/no/equipment/hantler','equipment_image_file' => 'hantler_2.png','equipment_created_datetime' => '2018-02-18 13:00:54','equipment_updated_datetime' => '2018-02-18 13:00:54','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '3','equipment_title' => 'Flatbenk','equipment_title_clean' => 'flatbenk','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/flatbenk','equipment_image_file' => 'flatbenk_3.png','equipment_created_datetime' => '2018-02-19 16:34:39','equipment_updated_datetime' => '2018-02-19 16:34:39','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '4','equipment_title' => 'Benkpress','equipment_title_clean' => 'benkpress','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '11','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/benkpress','equipment_image_file' => 'benkpress_4.png','equipment_created_datetime' => '2018-02-19 16:41:03','equipment_updated_datetime' => '2018-02-19 16:41:03','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '5','equipment_title' => 'Pull ups bar','equipment_title_clean' => 'pull_ups_bar','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '9','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-02-21 17:30:43','equipment_updated_datetime' => '2018-02-21 17:30:43','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '6','equipment_title' => 'Skr&aring;benk','equipment_title_clean' => 'skrabenk','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '11','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/skrabenk','equipment_image_file' => 'skrabenk_6.png','equipment_created_datetime' => '2018-03-10 17:32:51','equipment_updated_datetime' => '2018-03-10 17:32:51','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '8','equipment_title' => 'CrossOver','equipment_title_clean' => 'crossover','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '12','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-10 18:36:21','equipment_updated_datetime' => '2018-03-10 18:36:21','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '9','equipment_title' => 'Squat Stand','equipment_title_clean' => 'squat_stand','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/squat_stand','equipment_image_file' => 'squat_stand_9.png','equipment_created_datetime' => '2018-03-10 18:44:25','equipment_updated_datetime' => '2018-03-10 18:44:25','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '10','equipment_title' => 'Tredem&oslash;lle','equipment_title_clean' => 'tredemolle','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-10 22:59:04','equipment_updated_datetime' => '2018-03-10 22:59:04','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '11','equipment_title' => 'Pulsklokke','equipment_title_clean' => 'pulsklokke','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-10 23:12:21','equipment_updated_datetime' => '2018-03-10 23:12:21','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '12','equipment_title' => 'Vektstang','equipment_title_clean' => 'vektstang','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/vektstang','equipment_image_file' => 'vektstang_12.png','equipment_created_datetime' => '2018-03-17 22:19:21','equipment_updated_datetime' => '2018-03-17 22:19:21','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '13','equipment_title' => 'Smithmaskin','equipment_title_clean' => 'smithmaskin','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '11','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/smithmaskin','equipment_image_file' => 'smithmaskin_13.png','equipment_created_datetime' => '2018-03-18 08:50:04','equipment_updated_datetime' => '2018-03-18 08:50:04','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '14','equipment_title' => 'Dipsstativ','equipment_title_clean' => 'dipsstativ','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '12','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-18 09:02:27','equipment_updated_datetime' => '2018-03-18 09:02:27','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '15','equipment_title' => 'Beinpress','equipment_title_clean' => 'beinpress','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-19 21:49:39','equipment_updated_datetime' => '2018-03-19 21:49:39','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '16','equipment_title' => 'L&aring;rcurl','equipment_title_clean' => 'larcurl','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '16','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-20 16:53:28','equipment_updated_datetime' => '2018-03-20 16:53:28','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '17','equipment_title' => 'Benkpress maskin','equipment_title_clean' => 'benkpress_maskin','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '10','equipment_muscle_group_id_sub' => '11','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-20 17:03:02','equipment_updated_datetime' => '2018-03-20 17:03:02','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '18','equipment_title' => 'Tau','equipment_title_clean' => 'tau','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '22','equipment_muscle_group_id_sub' => '23','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-20 21:39:14','equipment_updated_datetime' => '2018-03-20 21:39:14','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '19','equipment_title' => 'Romaskin','equipment_title_clean' => 'romaskin','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '7','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 17:08:02','equipment_updated_datetime' => '2018-03-21 17:08:02','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '20','equipment_title' => 'Leggcurl','equipment_title_clean' => 'leggcurl','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '13','equipment_muscle_group_id_sub' => '15','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 17:20:02','equipment_updated_datetime' => '2018-03-21 17:20:02','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '21','equipment_title' => 'B&oslash;yd stang','equipment_title_clean' => 'boyd_stang','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '7','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 18:23:35','equipment_updated_datetime' => '2018-03-21 18:23:35','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '23','equipment_title' => 'Rett stang','equipment_title_clean' => 'rett_stang','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '1','equipment_muscle_group_id_sub' => '3','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 18:36:49','equipment_updated_datetime' => '2018-03-21 18:36:49','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '24','equipment_title' => 'Nedtrekk','equipment_title_clean' => 'nedtrekk','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '8','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 18:46:53','equipment_updated_datetime' => '2018-03-21 18:46:53','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '25','equipment_title' => 'V-Bar','equipment_title_clean' => 'v-bar','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '0','equipment_muscle_group_id_sub' => '0','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-21 18:59:08','equipment_updated_datetime' => '2018-03-21 18:59:08','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '26','equipment_title' => 'Treningsmatte','equipment_title_clean' => 'treningsmatte','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '22','equipment_muscle_group_id_sub' => '23','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-23 16:30:08','equipment_updated_datetime' => '2018-03-23 16:30:08','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '27','equipment_title' => 'Medisinball','equipment_title_clean' => 'medisinball','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '22','equipment_muscle_group_id_sub' => '23','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-23 16:49:10','equipment_updated_datetime' => '2018-03-23 16:49:10','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '28','equipment_title' => 'Treiningshjul','equipment_title_clean' => 'treiningshjul','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '22','equipment_muscle_group_id_sub' => '23','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-23 17:42:25','equipment_updated_datetime' => '2018-03-23 17:42:25','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '29','equipment_title' => 'Rygghevstativ','equipment_title_clean' => 'rygghevstativ','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '9','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => NULL,'equipment_image_path' => NULL,'equipment_image_file' => NULL,'equipment_created_datetime' => '2018-03-23 18:29:11','equipment_updated_datetime' => '2018-03-23 18:29:11','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL),
  array('equipment_id' => '30','equipment_title' => 'Pull ups belte','equipment_title_clean' => 'pull_ups_belte','equipment_user_id' => '1','equipment_language' => 'no','equipment_muscle_group_id_main' => '5','equipment_muscle_group_id_sub' => '9','equipment_muscle_part_of_id' => NULL,'equipment_type_id' => NULL,'equipment_text' => '','equipment_image_path' => '_uploads/exercises/no/equipment/pull_ups_belte','equipment_image_file' => 'pull_ups_belte_30.png','equipment_created_datetime' => '2018-03-23 19:10:15','equipment_updated_datetime' => '2018-03-23 19:10:15','equipment_user_ip' => '81.166.225.197','equipment_uniqe_hits' => '0','equipment_uniqe_hits_ip_block' => '','equipment_likes' => '0','equipment_dislikes' => '0','equipment_rating' => '0','equipment_rating_ip_block' => NULL,'equipment_number_of_comments' => '0','equipment_reported' => NULL,'equipment_reported_checked' => NULL,'equipment_reported_reason' => NULL)
);

		$datetime = date("Y-m-d H:i:s");
		foreach($stram_exercise_equipments as $v){
			
			$equipment_title = $v["equipment_title"];
			$equipment_title_clean = $v["equipment_title_clean"];
			$equipment_user_id = $v["equipment_user_id"];
			$equipment_language = $v["equipment_language"];
			$equipment_muscle_group_id_main = $v["equipment_muscle_group_id_main"];
			$equipment_muscle_group_id_sub = $v["equipment_muscle_group_id_sub"];

			$equipment_muscle_part_of_id = $v["equipment_muscle_part_of_id"];
			if($equipment_muscle_part_of_id == ""){
				$equipment_muscle_part_of_id = "0";
			}
			$equipment_type_id = $v["equipment_type_id"];
			if($equipment_type_id == ""){
				$equipment_type_id = "0";
			}
			$equipment_text = $v["equipment_text"];
			$equipment_image_path = $v["equipment_image_path"];
			$equipment_image_file = $v["equipment_image_file"];
		
			mysqli_query($link, "INSERT INTO $t_exercise_equipments
			(equipment_id, equipment_title, equipment_title_clean, equipment_user_id, equipment_language, equipment_muscle_group_id_main, equipment_muscle_group_id_sub, 
equipment_muscle_part_of_id, equipment_type_id, equipment_text, equipment_image_path, equipment_image_file, equipment_created_datetime, equipment_updated_datetime) 
			VALUES 
			(NULL, '$equipment_title', '$equipment_title_clean', '$equipment_user_id', '$equipment_language', '$equipment_muscle_group_id_main', '$equipment_muscle_group_id_sub', 
		'$equipment_muscle_part_of_id', '$equipment_type_id', '$equipment_text', '$equipment_image_path', '$equipment_image_file', '$datetime', '$datetime')
			")
			or die(mysqli_error($link));


		}

	}
	echo"
	<!-- //equipments -->



";
?>