<?php
/**
*
* File: _admin/_inc/exercises/_liquibase/index.php
* Version 1.0.0
* Date 12:57 24.03.2021
* Copyright (c) 2021 Sindre Andre Ditlefsen
* License: http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/
/*- Access check ----------------------------------------------------------------------- */
if(!(isset($define_access_to_control_panel))){
	echo"<h1>Server error 403</h1>";
	die;
}

/*- Tables ---------------------------------------------------------------------------- */

$result = mysqli_query($link, "DROP TABLE IF EXISTS $t_exercise_index") or die(mysqli_error($link)); 


echo"

	<!-- exercises -->
	";
	$query = "SELECT * FROM $t_exercise_index";
	$result = mysqli_query($link, $query);
	if($result !== FALSE){
		// Count rows
		$row_cnt = mysqli_num_rows($result);
		echo"
		<p>$t_exercise_index: $row_cnt</p>
		";
	}
	else{

		mysqli_query($link, "CREATE TABLE $t_exercise_index(
	  	 exercise_id INT NOT NULL AUTO_INCREMENT,
	 	  PRIMARY KEY(exercise_id), 
	  	   exercise_title VARCHAR(250),
	  	   exercise_title_clean VARCHAR(250),
	  	   exercise_title_alternative VARCHAR(250),
	  	   exercise_user_id INT,
	  	   exercise_language VARCHAR(20),
	  	   exercise_muscle_group_id_main INT,
	  	   exercise_muscle_group_id_sub INT,
	  	   exercise_muscle_part_of_id INT,
	  	   exercise_equipment_id  INT,
	  	   exercise_type_id INT,
	  	   exercise_level_id INT,
	  	   exercise_text TEXT,
	  	   exercise_preparation TEXT,
	  	   exercise_guide TEXT,
	  	   exercise_important TEXT,
	  	   exercise_created_datetime DATETIME,
	  	   exercise_updated_datetime DATETIME,
	  	   exercise_user_ip VARCHAR(250),
	  	   exercise_uniqe_hits INT,
	  	   exercise_uniqe_hits_ip_block TEXT,
	  	   exercise_likes INT,
	  	   exercise_dislikes INT,
	  	   exercise_rating INT,
	  	   exercise_rating_ip_block TEXT,
	  	   exercise_number_of_comments INT,
	  	   exercise_reported INT,
	  	   exercise_reported_checked INT,
	  	   exercise_reported_reason TEXT,
	  	   exercise_last_viewed DATETIME)")
		   or die(mysqli_error());
$stram_exercise_index = array(
  array('exercise_id' => '1','exercise_title' => 'Bulgarsk utfall','exercise_title_clean' => 'bulgarsk_utfall','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '3','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn frem et par manualer. Hold de med hÃ¥ndflatene mot hverandre. StÃ¥ i en forskjÃ¸vet holdning med den venstre foten foran din hÃ¸yre side. FÃ¸ttene skal vÃ¦re 0,5-1 meter fra hverandre. Kun vristen foten skal plasseres pÃ¥ benken. Kneet foran skal ha en liten bÃ¸y.</p>','exercise_guide' => '<p>Senk kroppen din sÃ¥ langt du kan. Det bakre kneet skal nesten berÃ¸re gulvet. Hold overkroppen sÃ¥ oppreist som mulig og korsryggen naturlig buet. Pause, og skyv deg tilbake til startposisjon sÃ¥ raskt som mulig. FullfÃ¸r repitisjoner med venstre fot, ogsÃ¥ med hÃ¸yre fot.</p>','exercise_important' => '<ul><li>Hvis foten din er pÃ¥ en hÃ¸yere benk vil treningen vÃ¦re hardere.</li>
</ul>','exercise_created_datetime' => '2018-02-18 12:42:22','exercise_updated_datetime' => '2018-02-19 16:38:45','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '2','exercise_title' => 'Triceps nedtrekk tau i kabel','exercise_title_clean' => 'triceps_nedtrekk_tau_i_kabel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '3','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => NULL,'exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Ta tak i tauet og dra den ned til forsiden av kroppen.</p>','exercise_guide' => '<p>Hold overarmene festet til siden av overkroppen din, utvide armene til Ã¥ skyve tauet ned. Stopp nÃ¥r albuene er i maks posisjon og reverser sÃ¥ bevegelsen sakte tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ã˜velsen skal gi kontinuerlig motstand og triceps skal ha stimulans gjennom hele bevegelsen.</li>
</ul>','exercise_created_datetime' => '2018-02-18 12:43:25','exercise_updated_datetime' => '2018-03-21 18:34:27','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '3','exercise_title' => 'Biceps curl med EZ stang','exercise_title_clean' => 'biceps_curl_med_ez_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '2','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '1','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Last vektstangen med vekter og plasser pÃ¥ sikkerhetskrager. Ta tak i vektstangen med et grep som er skulderbredde. StÃ¥ oppreist med flate overarmer og albuer.</p>','exercise_guide' => '<p>BÃ¸y albuen for Ã¥ lÃ¸fte vekten oppover med biceps. Overarmer og albuer bÃ¸r ligge intill siden pÃ¥ kroppen. Ved topposisjon reverseres bevegelsen langsomt tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<p>Mange idrettsutÃ¸vere velger Ã¥ benytte vekstangen EZ, noe som er bedre for hÃ¥ndleddet. Vekstangen EZ er litt bÃ¸yd sÃ¥ hÃ¥ndleddene slipper sÃ¥ mye rotasjon under Ã¸velsen.Â </p>','exercise_created_datetime' => '2018-02-18 12:43:29','exercise_updated_datetime' => '2018-02-19 17:56:44','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '4','exercise_title' => 'Bicepscurl med hantler','exercise_title_clean' => 'bicepscurl_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '2','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Hold hantlene i armene.</p>','exercise_guide' => '<p>La armene henge ned pÃ¥ sidene. Tomlene skal peke bort fra kroppen. Du vil holde dette hÃ¥ndstilling gjennom hele bevegelsen som det ikke bÃ¸r vÃ¦re noen vridning av hendene nÃ¥r de kommer opp. Dette vil vÃ¦re utgangspunktet.</p>
<p>Trekk opp begge hantlene samtidig. Ikke svinge armene eller bruke momentum. Hold en kontrollert bevegelse hele tiden. GÃ¥ tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Ikke utvid armene helt ettersom du kan skade albuene.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">SÃ¸rg for at bevegelsene er langsomme slik at du unngÃ¥r skade.</p>
</li>
</ul>','exercise_created_datetime' => '2018-02-18 12:56:53','exercise_updated_datetime' => '2018-02-19 17:56:49','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '5','exercise_title' => 'Benkpress','exercise_title_clean' => 'benkpress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '11','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '4','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Last vekter pÃ¥ vektstang og legg pÃ¥ sikkerhetskrager. Ligg flatt pÃ¥ benken med hÃ¦lene i bakken. Grip vektstangen med en litt bredere grep enn skulderne. LÃ¸ft av vektstangen fra stativet.</p>','exercise_guide' => '<p>Styr vektstang ned til brystet, slik at armene gÃ¥r ut nitti grader fra overkroppen. Trykk vektstangen opp igjen slik at armene utvides helt.</p>','exercise_important' => '<ul><li>Hvis du trener alene er det greiest og ikke bruke sikkerhetskragene, da man enklere kan fÃ¥ av vektene hvis man har lastet pÃ¥ for mye. Det anbefales at noen stÃ¥r bak og kan hjelpe til hvis du ikke klarer Ã¥ ta opp stangen.</li>
</ul>','exercise_created_datetime' => '2018-02-19 16:41:21','exercise_updated_datetime' => '2018-02-19 17:53:48','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '7','exercise_title' => 'Pull ups','exercise_title_clean' => 'pull_ups','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '9','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '5','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '','exercise_guide' => '<p>Ta et grep pÃ¥ stangen som er litt bredere en skuldrene. HÃ¥ndflatene skal vÃ¦re vendt bort fra deg. Heng fritt, med armene full utstrukket. Trekk kroppen opp slik at halsen nÃ¥r nivÃ¥et av stangen, og gÃ¥ sakte ned til startposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Haken skal over stangen nÃ¥r man er Ã¸verst i bevegelsen.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Senker man seg sakte ned, 20-30 sekunder vil man kunne Ã¸ke repitisjoner over tid.</p>
</li>
</ul>','exercise_created_datetime' => '2018-02-21 17:20:42','exercise_updated_datetime' => '2018-02-21 17:20:42','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '1','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '8','exercise_title' => 'Armhevninger','exercise_title_clean' => 'armhevninger','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => NULL,'exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Sett hendene med en litt bredere avstand enn skulderbredde. Kroppen skal vÃ¦re rett, fra hodet og til hÃ¦lene. Baken skal ikke stikke opp eller vÃ¦re senket ned.</p>','exercise_guide' => '<p>FÃ¸r deg selv ned slik at albuene fÃ¥r en 90 graders vinkel. NÃ¥r brystet berÃ¸rer gulvet holder du litt og gÃ¥r tilbake til utgangspunkt.</p>','exercise_important' => '<ul><li>Ikke juks pÃ¥ de siste push-upsene i settet ditt. NÃ¥r man er sliten er det lett Ã¥ gjÃ¸re feil pÃ¥ de siste repitisjonene. Stopp opp, skriv opp hvor mange du klarte og slÃ¥ antallet neste gang.</li>
</ul>','exercise_created_datetime' => '2018-02-21 17:44:04','exercise_updated_datetime' => '2018-02-21 17:44:04','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '9','exercise_title' => 'Supermann','exercise_title_clean' => 'supermann','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '9','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => NULL,'exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p><span lang="no" xml:lang="no"><span>Ligg flatt pÃ¥ magen med armene strakt ut foran deg.</span><br /></span></p>','exercise_guide' => '<p><span lang="no" xml:lang="no"><span>LÃ¸ft armene og beina av gulvet og hold denne posisjonen i 2 sekunder.</span><br /><span>GÃ¥ tilbake til startposisjonen pÃ¥ gulvet.</span><br /></span></p>','exercise_important' => '','exercise_created_datetime' => '2018-03-10 17:16:04','exercise_updated_datetime' => '2018-03-10 17:16:04','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '10','exercise_title' => 'Skr&aring; hantlepress','exercise_title_clean' => 'skra_hantlepress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '11','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '6','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p><span lang="no" xml:lang="no">Finn en skrÃ¥benk pÃ¥ 30 grader. <br /></span></p>
<p><span lang="no" xml:lang="no">Ha ett sett manualer med passende vekt. Sitt pÃ¥ enden av en skrÃ¥benk og la manualene hvile pÃ¥ lÃ¥rene. Len deg tilbake pÃ¥ benken, og bringer lÃ¥rene opp slik at du fÃ¥r manualene over deg. Ligg pÃ¥ bneken med fÃ¸ttene pÃ¥ gulvet, med manualer utvidet over brystet. </span></p>','exercise_guide' => '<p>Senk manualene sakte til siden av brystet, slik at overarmene er parallelt med bakken og er vinkelrett pÃ¥ overkroppen. Press brystet og strekk armene slik at manualene gÃ¥r oppover. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ã˜velsen skal ogsÃ¥ trene koordinasjon og stabilisering.</li>
</ul>','exercise_created_datetime' => '2018-03-10 17:29:56','exercise_updated_datetime' => '2018-03-10 17:29:56','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '11','exercise_title' => 'Hantlepress','exercise_title_clean' => 'hantlepress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '3','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Ha ett sett manualer med passende vekt. Sitt pÃ¥ enden av en benk og la manualene hvile pÃ¥ lÃ¥rene. Len deg tilbake pÃ¥ benken, og bringer lÃ¥rene opp slik at du fÃ¥r manualene over deg. Ligg pÃ¥ bneken med fÃ¸ttene pÃ¥ gulvet, med manualer utvidet over brystet.</p>','exercise_guide' => '<p>Senk manualene sakte til siden av brystet, slik at overarmene er parallelt med bakken og er vinkelrett pÃ¥ overkroppen. Press brystet og strekk armene slik at manualene gÃ¥r oppover. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ã˜velsen skal ogsÃ¥ trene koordinasjon og stabilisering.</li>
</ul>','exercise_created_datetime' => '2018-03-10 18:19:18','exercise_updated_datetime' => '2018-03-10 18:19:18','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '12','exercise_title' => 'Skulderpress med hantler','exercise_title_clean' => 'skulderpress_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '20','exercise_muscle_group_id_sub' => '21','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>LÃ¸ft en manualer pÃ¥ hver side av skuldrene. Overarmene skal vÃ¦re pÃ¥ linje med hverandre.</p>','exercise_guide' => '<p>Fra startposisjonen trykkes manualer oppover til armene er utvidet. Etter full forlengelse er oppnÃ¥dd reversere bevegelsen sakte til manualer er tilbake pÃ¥ startposisjon (rundt Ã¸rehÃ¸yde). Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ã˜velsen kan utfÃ¸res stÃ¥ende eller sittende. Nybegynner bÃ¸r starte sittende da stÃ¥ende Ã¸velse krever mye kjerne og stabilisering.</li>
</ul>','exercise_created_datetime' => '2018-03-10 18:27:22','exercise_updated_datetime' => '2018-03-10 18:27:22','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '13','exercise_title' => 'Kabel flyes h&oslash;ye','exercise_title_clean' => 'kabel_flyes_hoye','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '8','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Juster stativet slik at kablene er rett over skulderhÃ¸yden din.</p>','exercise_guide' => '<p><span lang="no" xml:lang="no"><span title="To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand. Â Â Â Â ">Hold kablene i hÃ¥nden og bÃ¸y deg fremover. </span></span></p>
<p><span lang="no" xml:lang="no"><span title="This will be your starting position. Â Â Â Â ">Strekk ut begge armene i en bred bue. Du skal fÃ¸le en strekk i brystet. Det er kun skulderen som skal arbeide med bevegelsen. Armene og brystet skal vÃ¦re i ro.</span></span></p>
<p><span lang="no" xml:lang="no"><span title="the movement should only occur at the shoulder joint. Â Â Â Â ">Pust ut og fÃ¸r armene fremover. </span></span></p>','exercise_important' => '<p>Du kan ogsÃ¥ utfÃ¸re lave kabel flyes.</p>','exercise_created_datetime' => '2018-03-10 18:32:22','exercise_updated_datetime' => '2018-03-10 18:32:22','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '14','exercise_title' => 'Kneb&oslash;y med stang','exercise_title_clean' => 'kneboy_med_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '9','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Last pÃ¥ vekter pÃ¥ en vektstang, hvis det er fÃ¸rste gang kan du starte uten vekter. Sett fÃ¸ttene rett under vekstangen. Skyt brystet ut. Den Ã¸vre delen av ryggen skal vÃ¦re stram.</p>
<p>LÃ¸ft deg opp og ta ett skritt tilbake. StÃ¥ rett med knÃ¦rne. LÃ¥s hoftene for maksimal stabilitet.</p>','exercise_guide' => '<p>Pust inn og skyv knÃ¦rne til siden og hoftene tilbake og ned. Hold pusten i bunnen. Ikke stopp, men raskt reverser bevegelsen ved Ã¥ kjÃ¸re hoftene rett opp. Hold knÃ¦rne ut, brystet opp og Ã¸vre rygg stramt. PÃ¥ toppen skal hoften og knÃ¦r vÃ¦re lÃ¥st. Pust ut pÃ¥ topen ta et sekund pause.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">FÃ¥ inn god teknikk mens fra starten av og med lette vekter. Ved store vekter kan smÃ¥ feil gjÃ¸re stor skade pÃ¥ kroppen.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Skal du bruke belte eller knebeskytter? FÃ¸rstnevnte hjelper til med Ã¥ stabilisere ryggraden ved Ã¥ Ã¸ke trykket pÃ¥ den. Den sistnevnte er bare en mÃ¥te Ã¥ lÃ¸fte mer vekt. Hvis du er nybegynner bÃ¸r du ikke bruke noen av disse, men heller fokusere pÃ¥ teknikk.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-10 18:40:45','exercise_updated_datetime' => '2018-03-10 18:40:45','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '15','exercise_title' => 'Markl&oslash;ft med hantler','exercise_title_clean' => 'markloft_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p><br /> Finn et sett med manualer. StÃ¥ oppreist og hold manualene foran hoftene.</p>','exercise_guide' => '<p>Ha en bÃ¸y i kneet. Senk manualene mot bakken ved Ã¥ bÃ¸ye hoften. Hold ryggen rett og brystet opp. NÃ¥r manualer er halvveis ved leggen skal Ã¸velsen reverseres. Gjenta Ã¸velsen for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Hold ryggen rett og brystet opp mens du utfÃ¸rer marklÃ¸ft.</li>
</ul>','exercise_created_datetime' => '2018-03-10 21:43:13','exercise_updated_datetime' => '2018-03-10 21:43:13','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '16','exercise_title' => 'Fronthev','exercise_title_clean' => 'fronthev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '20','exercise_muscle_group_id_sub' => '21','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Velg en Ã¸nskede hantler og hold de med skulderbredde. Ha en liten bÃ¸y i knÃ¦rne. Hold overkroppen oppreist og brystet ut og ta et dypt Ã¥ndedrag. Dette vil vÃ¦re utgangsstillingen.</p>','exercise_guide' => '<p>Holde armene rett og hev en og en hantel opp til Ã¸yehÃ¸yde (pust ut pÃ¥ vei opp). Hold skriven i et sekund pÃ¥ toppen og senk vekten ned samtidig som du puster inn. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Mange kaller Ã¸velsen bortkastet tid, da den fremre delen av skulderen allerede blir trent i andre press-Ã¸velser, slik som f.eks. benkpress.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-10 21:49:05','exercise_updated_datetime' => '2018-03-10 21:49:05','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '17','exercise_title' => 'Intervaller 400 m x 12, 1 min pause','exercise_title_clean' => 'intervaller_400_m_x_12__1_min_pause','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '10','exercise_type_id' => '5','exercise_level_id' => '2','exercise_preparation' => '<p>Tenk ut en fart du skal klare Ã¥ holde i 400 meter.</p>','exercise_guide' => '<p>LÃ¸p i rask hastighet i 400 meter.</p>
<p>Ta et minutt pause ved at du gÃ¥r pÃ¥ 6 -7 km/h.</p>
<p>Gjenta 12 ganger.</p>','exercise_important' => '<p>Du skal ligge hÃ¸yt pÃ¥ laktatgrensen. Denne ligger pÃ¥ topp pÃ¥ grensen, over 1,6 km intervallene.</p>','exercise_created_datetime' => '2018-03-10 22:50:29','exercise_updated_datetime' => '2018-03-10 22:50:29','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '18','exercise_title' => 'Lett joggetur','exercise_title_clean' => 'lett_joggetur','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '11','exercise_type_id' => '5','exercise_level_id' => '1','exercise_preparation' => '<p>Pulsklokke og headset.</p>','exercise_guide' => '<p>En lett joggetur splittes opp i tre ulike Ã¸kter slik at kroppen ikke venner seg til den. </p>
<p>FÃ¸rste turen/uken jogger du 8 km.<br />Andre turen/uken jogger du 9,6 km.<br />Tredje turen/uken jogger du 11,2 km.</p>
<p>Deretter starter du pÃ¥ fÃ¸rste uken igjen.</p>','exercise_important' => '<ul><li>En lett lÃ¸peÃ¸kt lÃ¸pes for restutisjon. Man skal holde et lavt tempo.</li>
<li>Pulsen skal ligge pÃ¥ rundt 60 %.</li>
</ul>','exercise_created_datetime' => '2018-03-10 23:08:29','exercise_updated_datetime' => '2018-03-10 23:16:38','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '19','exercise_title' => 'Intervaller 800 m x 6, 2 min pause','exercise_title_clean' => 'intervaller_800_m_x_6__2_min_pause','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '10','exercise_type_id' => '5','exercise_level_id' => '2','exercise_preparation' => '<p>Tenk deg en fart du skal klare i 800 m 6 ganger.</p>
<p>Sett mÃ¸llen pÃ¥ 1 i incline, skru pÃ¥ pulsklokken og favorittmusikken din.</p>','exercise_guide' => '<p>LÃ¸p 800 m. <br />Rask gange i 2 minutter. <br />Gjenta 6 ganger.</p>','exercise_important' => '<ul><li>Du skal klare alle intervallene. Hvis du ikke klarer alle har du for rask hastighet.</li>
<li>Du skal ligge hÃ¸yt pÃ¥ laktatgrensen. Denne ligger pÃ¥ topp pÃ¥ grensen, over 1,6 km intervallene.</li>
</ul>','exercise_created_datetime' => '2018-03-11 09:00:10','exercise_updated_datetime' => '2018-03-11 09:00:10','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '20','exercise_title' => 'Intervaller 1,6 km x 3, 3 min pause','exercise_title_clean' => 'intervaller_1_6_km_x_3__3_min_pause','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '10','exercise_type_id' => '5','exercise_level_id' => '2','exercise_preparation' => '<p>I disse lange intervallene skal du ligge over laktalgrensen i forhold til tempo kjÃ¸ringene. Du skal samtidig ligge lavere enn 400 meter og 800 meter intervallene.</p>
<p>MÃ¸llen skal stÃ¥ pÃ¥ incline 1 - 1,5.</p>','exercise_guide' => '<p>LÃ¸p 1,6 km.<br />Rask gange i 3 min.<br />Gjenta 3 ganger.</p>','exercise_important' => '<p>Ligg over laktalgrensen for melkesyredannelse pÃ¥ 1,6 km intervallene, men lavere enn 400 og 800 meters intrevallene.</p>','exercise_created_datetime' => '2018-03-11 09:04:56','exercise_updated_datetime' => '2018-03-11 09:04:56','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '21','exercise_title' => 'Tempo joggetur','exercise_title_clean' => 'tempo_joggetur','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '11','exercise_type_id' => '5','exercise_level_id' => '2','exercise_preparation' => '<p>Pulsklokke og headset.</p>','exercise_guide' => '<p>Tempo betyr at du skal ligge rett over grensen hvor kroppen produserer melkesyre. Denne joggetur splittes opp i tre ulike Ã¸kter slik at kroppen ikke venner seg til den.</p>
<p>FÃ¸rste turen/uken jogger du 9,6 km.<br />Andre turen/uken jogger du 11,2 km.<br />Tredje turen/uken jogger du 12,8 km.</p>
<p>Deretter starter du pÃ¥ fÃ¸rste uken igjen.</p>','exercise_important' => '<ul><li>Du skal kunne holde samme farten i hele tempoÃ¸kten.</li>
</ul>','exercise_created_datetime' => '2018-03-11 09:09:43','exercise_updated_datetime' => '2018-03-11 09:09:43','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '22','exercise_title' => 'Langkj&oslash;ring joggetur','exercise_title_clean' => 'langkjoring_joggetur','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '11','exercise_type_id' => '5','exercise_level_id' => '2','exercise_preparation' => '<p>Forebered din pulsklokke og favorittmusikk.</p>','exercise_guide' => '<p>Denne er den lengste joggeturen du trenger hvis du forbereder deg for 5 km. LangkjÃ¸ring splittes i tre ulike Ã¸kter:</p>
<p>FÃ¸rste uken 12,8 km.<br />Andre uken 14,5 km.<br />Tredje uken 16 km.<br />Deretter start pÃ¥ fÃ¸rste uken.</p>','exercise_important' => '<ul><li>
<p>Â Disse Ã¸ktene skal lÃ¸pes raskere en lett joggetur, men ikke raskere enn tempo joggetur.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-11 09:25:49','exercise_updated_datetime' => '2018-03-11 09:25:49','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '23','exercise_title' => 'Hammercurl med hantler','exercise_title_clean' => 'hammercurl_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '2','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Hold hantlene i armene.</p>','exercise_guide' => '<p>La armene henge ned pÃ¥ sidene. Tomlene skal peke bort fra kroppen. Du vil holde dette hÃ¥ndstilling gjennom hele bevegelsen som det ikke bÃ¸r vÃ¦re noen vridning av hendene nÃ¥r de kommer opp. Dette vil vÃ¦re utgangspunktet.</p>
<p>Trekk opp en og en hantel. Ikke svinge armene eller bruke momentum. Hold en kontrollert bevegelse hele tiden. GÃ¥ tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li style="margin:4px 0px 6px 0px;padding:0;">Â Ikke utvid armene helt ettersom du kan skade albuene.</li>
<li style="margin:4px 0px 6px 0px;padding:0;">SÃ¸rg for at bevegelsene er langsomme slik at du unngÃ¥r skade.</li>
</ul>','exercise_created_datetime' => '2018-03-12 16:51:08','exercise_updated_datetime' => '2018-03-12 16:51:08','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '24','exercise_title' => 'Markl&oslash;ft med stang','exercise_title_clean' => 'markloft_med_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '12','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p>Sett opp en vektstang med Ã¸nsket vekt pÃ¥ gulvet foran deg. FÃ¸ttene skal ca ha en skulders avstand. Sitt pÃ¥ huk ved Ã¥ bÃ¸ye knÃ¦rne til du er langt nok nede til Ã¥ fÃ¥ et grep pÃ¥ vektstang. Ta tak i vektstang med overhandsgrep som er litt bredere enn skulderbredde.</p>','exercise_guide' => '<p>Ta et dyp innpust. Bruk beina til Ã¥ lÃ¸fte vekten oppover til du stÃ¥r oppreist. NÃ¥r stangen nÃ¥r knÃ¦rne retter du deg opp. Ta en kort pause pÃ¥ toppen av bevegelsen for Ã¥ sikre at optimal sammentrekning er oppnÃ¥dd. KnÃ¦rne skal ikke vÃ¦re lÃ¥st. Senk vekten tilbake til startposisjon. Pust og gjÃ¸r deg klar for en ny repitisjon.</p>','exercise_important' => '<p>Hvis du ikke opprettholder riktig teknikk under marklÃ¸ft vil du til slutt skade deg. ForhÃ¸r deg med en personlig trener.</p>','exercise_created_datetime' => '2018-03-17 22:17:01','exercise_updated_datetime' => '2018-03-17 22:17:01','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '25','exercise_title' => 'Utfall med stang','exercise_title_clean' => 'utfall_med_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '12','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>StÃ¥ med overkroppen oppreist med en vektstang over skuldrene. Denne stillingen vil vÃ¦re utgangspunktet for Ã¸velsen.</p>','exercise_guide' => '<p>GÃ¥ ett skritt frem med hÃ¸yre bein pÃ¥ ca 0,5 meter og senk overkroppen ned. Brystet skal skytes ut og samtidig mÃ¥ balansen opprettholdes. Bruk hovedsakelig hÃ¦len av foten, skyv opp og gÃ¥ tilbake til startposisjon som du puster ut. Repeter bevegelsen og utfÃ¸r deretter med venstre ben.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Du kan veksle fot hver gang. For eksempel kan du fÃ¸rst ta en reptisjon med hÃ¸yre fot, ogsÃ¥ en med venstre fot og sÃ¥ videre</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Hvis du har problemer med balansen kan du gjÃ¸re Ã¸velsen uten vektstang. </p>
</li>
</ul>','exercise_created_datetime' => '2018-03-18 08:23:49','exercise_updated_datetime' => '2018-03-18 08:23:49','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '26','exercise_title' => 'Omvendt roing i smithmaskin','exercise_title_clean' => 'omvendt_roing_i_smithmaskin','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '7','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '13','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p><span lang="no" xml:lang="no"><span>Sett en stang i midjehÃ¸yde. <br />La fÃ¸ttene hvile pÃ¥ bakken og grip tak i stangen. </span><br />Klem skulderbladene sammen og trekk brystet opp til stangen.</span></p>','exercise_guide' => '<p>Press deg opp til stangen slik at brystet er borti den.</p>
<p>Senk deg sÃ¥ ned igjen og repeter.</p>','exercise_important' => '<ul><li>Hold kroppen rett under Ã¸velsen.</li>
</ul>','exercise_created_datetime' => '2018-03-18 08:41:52','exercise_updated_datetime' => '2018-03-18 08:50:09','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '27','exercise_title' => 'Dips','exercise_title_clean' => 'dips','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '14','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Ta tak i sidene pÃ¥ dips-stativet. Press deg oppover til startposisjonen. FÃ¸ttene kan vÃ¦re krysset over bak deg, med knÃ¦rne bÃ¸yd.</p>','exercise_guide' => '<p>Senk kroppen din ned kontrollert helt til triceps er parallellt med gulvet. Kroppen skal vÃ¦re fremoverbÃ¸yd med omentrent ca 45 grader. Brystet og skuldrene skal vÃ¦re strekt. Fortsett Ã¥ len deg litt fremover samtidig som du skyver deg opp til startposisjonen.</p>','exercise_important' => '<ul><li>NÃ¥r du utfÃ¸rer dips kan beina vÃ¦re bÃ¸yd, krysset eller rett, avhengig av hvor hÃ¸yt opep fra gulvet du er.</li>
</ul>','exercise_created_datetime' => '2018-03-18 09:00:54','exercise_updated_datetime' => '2018-03-18 09:00:54','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '28','exercise_title' => 'Kabel flyes lave','exercise_title_clean' => 'kabel_flyes_lave','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '8','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Juster stativet slik at kablene er pÃ¥ det laveste nivÃ¥et.</p>','exercise_guide' => '<p><span lang="no" xml:lang="no"><span title="To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand. Â Â Â Â ">Hold kablene i hÃ¥nden og bÃ¸y deg fremover. </span></span></p>
<p><span lang="no" xml:lang="no"><span title="This will be your starting position. Â Â Â Â ">Strekk ut begge armene i en bred bue. Du skal fÃ¸le en strekk i brystet. Det er kun skulderen som skal arbeide med bevegelsen. Armene og brystet skal vÃ¦re i ro.</span></span></p>
<p><span lang="no" xml:lang="no"><span title="the movement should only occur at the shoulder joint. Â Â Â Â ">Pust ut og fÃ¸r armene fremover. </span></span></p>','exercise_important' => '<ul><li>Du kan ogsÃ¥ utfÃ¸re lave kabel hÃ¸ye.</li>
</ul>','exercise_created_datetime' => '2018-03-18 09:11:29','exercise_updated_datetime' => '2018-03-18 09:11:29','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '29','exercise_title' => 'Crunches','exercise_title_clean' => 'crunches','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '3','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Plasser en matte pÃ¥ gulvet. Du kan bruke en benk til Ã¥ ha beinene pÃ¥. En annen variant er bÃ¸yde knÃ¦r og fÃ¸ttene flatt pÃ¥ gulvet. BÃ¸y armene ved albuen og plassere hendene nÃ¦r Ã¸rene. Hold en avstand mellom haken og brystet hele tiden. Halsen skal forbli i en nÃ¸ytral posisjon.</p>','exercise_guide' => '<p>Hev skuldrene opp fra gulvet, bÃ¸ye den Ã¸vre delen av ryggen din mens den nedre del av ryggen forblir stasjonÃ¦r. NÃ¥r sammentrekning er nÃ¥dd skal du ha en pause pÃ¥ et sekund, og deretter sakte reversere tilbake til startposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Ikke bÃ¸y ryggen. Denne Ã¸velsen skal trene magen, ikke ryggen.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Denne Ã¸velse utvikler magemusklene, men fÃ¸rer ikke til spesifikk fettreduksjon fra magen. For fettreduksjon er det viktig at man fÃ¸lger et sundt kosthold.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-18 09:28:53','exercise_updated_datetime' => '2018-03-18 09:28:53','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '30','exercise_title' => 'Omvendt skr&aring; hantlepress','exercise_title_clean' => 'omvendt_skra_hantlepress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '6','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Ha ett sett manualer med passende vekt. Sitt pÃ¥ enden av en benk og la manualene hvile pÃ¥ lÃ¥rene. Len deg tilbake pÃ¥ benken. Ha en manual i hver hÃ¥nd. Ligg pÃ¥ bneken med fÃ¸ttene sikret i benken.</p>','exercise_guide' => '<p>Senk manualene sakte til siden av brystet, slik at overarmene er parallelt med bakken og er vinkelrett pÃ¥ overkroppen. Press brystet og strekk armene slik at manualene gÃ¥r oppover. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ã˜velsen skal ogsÃ¥ trene koordinasjon og stabilisering.</li>
</ul>','exercise_created_datetime' => '2018-03-18 09:38:23','exercise_updated_datetime' => '2018-03-18 09:38:23','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '31','exercise_title' => 'Liggende tricepspress','exercise_title_clean' => 'liggende_tricepspress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '3','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn en passende vekt pÃ¥ en manual. Legg deg pÃ¥ en benk med manualen i hÃ¥nden.</p>','exercise_guide' => '<p>Senk manualen ned over hodet.</p>
<p>LÃ¸ft manualen sÃ¥ opp igjen. Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Ikke overgÃ¥ deg selv. Denne Ã¸velsen er lett Ã¥ skade triceps pÃ¥, sÃ¥ ikke bruk for tunge vekter.</li>
</ul>','exercise_created_datetime' => '2018-03-18 15:03:59','exercise_updated_datetime' => '2018-03-18 15:03:59','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '32','exercise_title' => 'Flyes med hantler','exercise_title_clean' => 'flyes_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '12','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn to manualer og plasser de pÃ¥ lÃ¥rne dine.</p>
<p>Legg deg ned pÃ¥ en flatbenk.</p>','exercise_guide' => '<p>Beveg armene ut til siden, og sÃ¥ inn og opp igjen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-18 15:56:29','exercise_updated_datetime' => '2018-03-18 15:56:29','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '33','exercise_title' => 'Utfall med hantler','exercise_title_clean' => 'utfall_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '16','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>StÃ¥ med overkroppen oppreist med en manual i hver hÃ¥nd. Denne stillingen vil vÃ¦re utgangspunktet for Ã¸velsen.</p>','exercise_guide' => '<p>GÃ¥ ett skritt frem med hÃ¸yre bein pÃ¥ ca 0,5 meter og senk overkroppen ned. Brystet skal skytes ut og samtidig mÃ¥ balansen opprettholdes. Bruk hovedsakelig hÃ¦len av foten, skyv opp og gÃ¥ tilbake til startposisjon som du puster ut. Repeter bevegelsen og utfÃ¸r deretter med venstre ben.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Du kan veksle fot hver gang. For eksempel kan du fÃ¸rst ta en reptisjon med hÃ¸yre fot, ogsÃ¥ en med venstre fot og sÃ¥ videre</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Hvis du har problemer med balansen kan du gjÃ¸re Ã¸velsen uten manualer.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-18 16:05:59','exercise_updated_datetime' => '2018-03-18 16:05:59','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '34','exercise_title' => 'Sidehev','exercise_title_clean' => 'sidehev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '20','exercise_muscle_group_id_sub' => '21','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Velg lette manualer og stÃ¥ med rett rygg. Hold manualer i armene med hÃ¥ndflatene mot deg.</p>','exercise_guide' => '<p>LÃ¸ft manualene til din side med en liten bÃ¸y pÃ¥ albuen. Fortsett Ã¥ gÃ¥ opp til du armene er parallelt med gulvet. Ta et sekund pause pÃ¥ toppen og senk manualene tilbake langsomt ned til startposisjon. Gjenta etter treningsprogrammets antall repetisjoner.</p>','exercise_important' => '<p style="padding-bottom:0;margin-bottom:0;">Â </p>
<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Hold overkroppen i ro (ikke sving med kroppen).</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-18 16:13:35','exercise_updated_datetime' => '2018-03-18 16:13:35','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '35','exercise_title' => 'Beinspark (Leg extension)','exercise_title_clean' => 'beinspark_leg_extension','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '15','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Juster benstrekk/benekstensjon apparatet slik at det er tilpasset din hÃ¸yde.</p>','exercise_guide' => '<p>Press opp med beina, samtidig som du holder ryggen din rett.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-19 21:47:17','exercise_updated_datetime' => '2018-03-20 16:28:44','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '36','exercise_title' => 'Beinpress (Leg press)','exercise_title_clean' => 'beinpress_leg_press','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '15','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg pÃ¥ eventuelle vekter pÃ¥ beinpressmaskinen. Sett deg ned i maskinen.</p>','exercise_guide' => '<p><span lang="no" xml:lang="no">Ta bort sikkerhetsbÃ¸ylene og press platen til den er helt oppe. KnÃ¦rne skal ikke lÃ¥se seg. Kroppen og beina dine skal danne nesten 90 graders vinkel.<br /></span></p>
<p><span lang="no" xml:lang="no">La platen gli nedover samtidig som du bÃ¸yer knÃ¦rne.</span></p>
<p><span lang="no" xml:lang="no">Skyv sÃ¥ platen opp igjen.</span></p>
<p><span lang="no" xml:lang="no">Gjenta for Ã¸nskede antall repitisjoner. </span></p>','exercise_important' => '<p>Ikke strekk beina dine ut slik at knÃ¦rne lÃ¥ser seg. Dette kan fÃ¸re til veldig farlige skader.</p>','exercise_created_datetime' => '2018-03-20 16:30:19','exercise_updated_datetime' => '2018-03-20 16:30:19','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '37','exercise_title' => 'Franskpress','exercise_title_clean' => 'franskpress','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '3','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '1','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p>Bruk en Ez-stang. Last pÃ¥ Ã¸nsket vekter pÃ¥ stangen.</p>
<p>Legg deg pÃ¥ rygg pÃ¥ en flat benk. La Ez-stangen ligge pÃ¥ magen din.</p>
<p>LÃ¸ft opp stangen til over hodet.</p>','exercise_guide' => '<p>Senk stangen ned bak hodet ditt, og press sÃ¥ opp.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>PÃ¥ engelsk heter denne Ã¸velsen Skull Crushers.</li>
<li>Du kan starte med triceps nedpress fÃ¸r denne Ã¸velsen da denne er teknisk krevende.</li>
</ul>','exercise_created_datetime' => '2018-03-20 16:41:07','exercise_updated_datetime' => '2018-03-20 16:48:30','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '38','exercise_title' => 'L&aring;rcurl (Leg curl)','exercise_title_clean' => 'larcurl_leg_curl','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '16','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '16','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still inn leg curl maskinen til Ã¸nsket vekt. Legg deg ned pÃ¥ maskinen pÃ¥ magen.</p>','exercise_guide' => '<p>Hev leggene dine. Repeter for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-20 16:51:07','exercise_updated_datetime' => '2018-03-20 16:51:07','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '39','exercise_title' => 'Benkpress i maskin','exercise_title_clean' => 'benkpress_i_maskin','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '11','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '17','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still inn maskinen til Ã¸nsket vekt. Ha fÃ¸ttene plantet pÃ¥ gulvet. Ta et godt grep litt bredere en skuldrene. LÃ¸ft opp brystet.</p>','exercise_guide' => '<p>Press hÃ¥ntakene ut fra kroppen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-20 16:59:33','exercise_updated_datetime' => '2018-03-20 16:59:33','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '40','exercise_title' => 'En arms bicepscurl med hantel','exercise_title_clean' => 'en_arms_bicepscurl_med_hantel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '2','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '6','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn en passende vekt. Sett opp en benk slik at du fÃ¥r en god skrÃ¥ning.</p>','exercise_guide' => '<p>Ha armen hvile over benken og hold i en hantel.</p>
<p>Trekk hantelen mot deg. Strekk sÃ¥ ut armen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Denne Ã¸velsen skal trene biceps.</li>
</ul>','exercise_created_datetime' => '2018-03-20 17:33:54','exercise_updated_datetime' => '2018-03-20 17:33:54','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '41','exercise_title' => 'En arms tricepspress med hantel','exercise_title_clean' => 'en_arms_tricepspress_med_hantel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '3','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn en passende vekt pÃ¥ en manual. Denne Ã¸velsen kan enten gjÃ¸res sittende eller stÃ¥ende.</p>','exercise_guide' => '<p>Trekk hantelen over og bak hodet ditt. Press sÃ¥ armen opp i vÃ¦ret.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Denne Ã¸velsen kan vÃ¦re veldig tung, sÃ¥ du bÃ¸r starte med en lav vekt.</li>
</ul>','exercise_created_datetime' => '2018-03-20 17:45:36','exercise_updated_datetime' => '2018-03-20 17:45:36','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '42','exercise_title' => 'Goblet squats','exercise_title_clean' => 'goblet_squats','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn Ã¸nsket vekt i hantel eller kettlebell.</p>','exercise_guide' => '<p>NÃ¥r du holder manualen i hendene kan du lage en "sette deg ned"-bevegelse. Rett deg sÃ¥ opp igjen.</p>
<p>Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Hold ryggen rett under Ã¸velsen.</li>
<li>PÃ¥ engelsk heter denne Ã¸velsen plie squat with dumbbell.</li>
</ul>','exercise_created_datetime' => '2018-03-20 18:10:02','exercise_updated_datetime' => '2018-03-20 18:10:02','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '43','exercise_title' => 'Biceps curl med EZ stang over benk','exercise_title_clean' => 'biceps_curl_med_ez_stang_over_benk','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '2','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '1','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Last vektstangen med vekter og plasser pÃ¥ sikkerhetskrager. Ta tak i vektstangen med et grep som er skulderbredde. Ha flate overarmer og albuer.</p>','exercise_guide' => '<p>BÃ¸y albuen for Ã¥ lÃ¸fte vekten oppover med biceps. Overarmer og albuer bÃ¸r ligge intill siden pÃ¥ kroppen. Ved topposisjon reverseres bevegelsen langsomt tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Denne Ã¸velsen kan ogsÃ¥ gjÃ¸res stÃ¥ende.</li>
</ul>','exercise_created_datetime' => '2018-03-20 18:21:51','exercise_updated_datetime' => '2018-03-20 18:21:51','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '44','exercise_title' => 'St&aring;ende roing med stang','exercise_title_clean' => 'staende_roing_med_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '8','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '12','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p>Finn en olympisk stang. Legg pÃ¥ Ã¸nskete vekter.</p>
<p>Still deg foran vektstangen og ha en rett rygg.</p>','exercise_guide' => '<p>BÃ¸y deg litt fremover og trekk stangen mot deg. Senk den sÃ¥ ned igjen.</p>
<p>Gjenta for Ã¸nskete antall repitisjoner.</p>','exercise_important' => '<ul><li>PÃ¥ engelsk heter denne Ã¸velsen rear deltoid row with barbell.</li>
</ul>','exercise_created_datetime' => '2018-03-20 18:26:32','exercise_updated_datetime' => '2018-03-20 18:26:32','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '45','exercise_title' => 'En arms roing med hantler','exercise_title_clean' => 'en_arms_roing_med_hantler','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '7','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn en passende manual og en flat benk. <br />Putt det ene kneet oppÃ¥ benken og stÃ¸tt opp kroppen med en ene hÃ¥nden. <br />Ha hantlen i den andre hÃ¥nden.</p>','exercise_guide' => '<p>LÃ¸ft opp hantlen til siden av kroppen. <br />Senk hantlen ned igjen i en kontrollert tempo.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Hold en rett rygg under denne Ã¸velsen.</li>
<li>Husk at du skal trene ryggen, sÃ¥ ikke svai med kroppen under opptrekket av hantelen.</li>
</ul>','exercise_created_datetime' => '2018-03-20 21:26:30','exercise_updated_datetime' => '2018-03-20 21:26:30','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '46','exercise_title' => 'Sittende ab crunches i kabel','exercise_title_clean' => 'sittende_ab_crunches_i_kabel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '18','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still inn Ã¸nsket vekt i maskinen. Fest pÃ¥ et tau. Still deg med ryggen til maskinen og ta tak i tauet.</p>','exercise_guide' => '<p>GÃ¥ ned i sitte-stilling og trekk ned vekten. <br />Slipp sÃ¥ vekten opp i en kontrollert bevegelse. </p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Hendene skal vÃ¦re i Ã¸rehÃ¸yde hele tiden.</li>
<li>Hvis du har ryggproblemer bÃ¸r du kontakte en personlig trener for veiledning.</li>
</ul>','exercise_created_datetime' => '2018-03-20 21:36:34','exercise_updated_datetime' => '2018-03-20 21:36:34','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '47','exercise_title' => 'Roing','exercise_title_clean' => 'roing','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '7','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '19','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Sitt pÃ¥ setet med en oppreist kropp. Ryggen skal vÃ¦re rett og knÃ¦rne skal vÃ¦re bÃ¸yd. Ta tak i hÃ¥ndtakene med armene utstrakt foran deg.</p>','exercise_guide' => '<p>Trekk hÃ¥ndtaket mot magen og oppretthold en god holdning (rett rygg, ikke bÃ¸y deg fremover). NÃ¥r hÃ¥ndtaket nÃ¥r magen reverseres bevegelsen langsomt tilbake til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<p style="padding-bottom:0;margin-bottom:0;">Â </p>
<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Ikke sving eller rykk i vektene i lÃ¸pet av Ã¸velsen.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Ikke hent moment, det vil si bÃ¸y deg fremover i Ã¸velsen.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-21 17:05:43','exercise_updated_datetime' => '2018-03-21 17:05:43','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '48','exercise_title' => 'Sittende leggcurl','exercise_title_clean' => 'sittende_leggcurl','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '13','exercise_muscle_group_id_sub' => '15','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '20','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still inn vektene til Ã¸nsket styrkegrad. Still inn apparatet slik at den passer din hÃ¸yde.</p>','exercise_guide' => '<p>Press legge ned og mot deg. Slipp sÃ¥ lÃ¸s i et kontrollert tempo.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Ikke lÃ¥s kneet pÃ¥ hvilestilling.</li>
</ul>','exercise_created_datetime' => '2018-03-21 17:18:10','exercise_updated_datetime' => '2018-03-21 17:18:10','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '49','exercise_title' => 'Shrugs','exercise_title_clean' => 'shrugs','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '20','exercise_muscle_group_id_sub' => '21','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn to manualer i passende vekt. Hold dem i hendene.</p>','exercise_guide' => '<p>Trekk skuldrene opp. Slipp sÃ¥ opp i et kontrollert tempo.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-21 17:25:06','exercise_updated_datetime' => '2018-03-21 17:25:06','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '50','exercise_title' => 'Sideb&oslash;y med hantel','exercise_title_clean' => 'sideboy_med_hantel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '2','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Hold en manual i hver hÃ¥nd. </p>','exercise_guide' => '<p>BÃ¸y deg ned til den ene siden. Rett deg sÃ¥ opp igjen, og bÃ¸y deg til andre siden.</p>
<p>Repeter for antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-21 17:38:42','exercise_updated_datetime' => '2018-03-21 17:38:42','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '51','exercise_title' => 'Sideplanke','exercise_title_clean' => 'sideplanke','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => NULL,'exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg deg pÃ¥ siden. Ha begge fÃ¸ttene oppÃ¥ hverandre. StÃ¸tt deg opp med den ene armen, rett under skulderen.</p>','exercise_guide' => '<p>LÃ¸ft deg opp og hold posisjonen. Ikke la hoftene falle til gulvet.</p>
<p>GjÃ¸r det samme for andre siden.</p>
<p>Repter for antall Ã¸nsket repitisjoner.</p>','exercise_important' => '<ul><li>H<span lang="no" xml:lang="no"><span>old hodet og nakken rett.</span> <br /></span></li>
</ul>','exercise_created_datetime' => '2018-03-21 17:46:08','exercise_updated_datetime' => '2018-03-21 17:46:08','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '52','exercise_title' => 'Benkpress i smithmaskin','exercise_title_clean' => 'benkpress_i_smithmaskin','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '10','exercise_muscle_group_id_sub' => '11','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '13','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Sett pÃ¥ Ã¸nskete vekter i smith maskinen.</p>
<p>Grip vektstangen med en litt bredere grep enn skulderne.</p>','exercise_guide' => '<p>Styr vektstang ned til brystet, slik at armene gÃ¥r ut nitti grader fra overkroppen. Trykk vektstangen opp igjen slik at armene utvides helt.</p>','exercise_important' => '<ul><li>Det anbefales at noen stÃ¥r bak og kan hjelpe til hvis du ikke klarer Ã¥ ta opp stangen.</li>
</ul>','exercise_created_datetime' => '2018-03-21 18:07:16','exercise_updated_datetime' => '2018-03-21 18:07:16','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '53','exercise_title' => 'St&aring;ende bicepscurl med stang i kabel','exercise_title_clean' => 'staende_bicepscurl_med_stang_i_kabel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '0','exercise_muscle_group_id_sub' => '0','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => NULL,'exercise_type_id' => '6','exercise_level_id' => '1','exercise_preparation' => '<p>Hekt pÃ¥ en flat stang pÃ¥ en kabel. Den skal vÃ¦re pÃ¥ det laveste nivÃ¥et. Still inn Ã¸nsket vekt.</p>
<p>StÃ¥ med beina i vanlig skulderavstand.</p>','exercise_guide' => '<p>Trekk stangen mot deg slik at biceps sammentrekker seg. Slipp sÃ¥ kontrollert opp igjen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => NULL,'exercise_created_datetime' => '2018-03-21 18:12:37','exercise_updated_datetime' => '2018-03-21 18:16:07','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '54','exercise_title' => 'St&aring;ende pushdown med b&oslash;yd stang','exercise_title_clean' => 'staende_pushdown_med_boyd_stang','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '7','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '21','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Finn en bÃ¸yd stang som du hekter pÃ¥ en kabel. Still kabelen slik at den er hÃ¸yere en deg.</p>','exercise_guide' => '<p>Ta tak i stangen og trekk den ned. Slipp sÃ¥ kontrollert opp igjen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Denne Ã¸velsen trener lats og armer.</li>
</ul>','exercise_created_datetime' => '2018-03-21 18:21:03','exercise_updated_datetime' => '2018-03-21 18:21:03','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '55','exercise_title' => 'Triceps nedtrekk stang i kabel','exercise_title_clean' => 'triceps_nedtrekk_stang_i_kabel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '1','exercise_muscle_group_id_sub' => '3','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '23','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Hekt pÃ¥ en stang i en kabel. <br />Still kabelen til over hodet ditt. <br />StÃ¥ med skulderavstand i beina. <br />Ta tak i stangen.</p>','exercise_guide' => '<p>Trekk kabelen ned mot gulvet. Slipp den opp i et kontrollert tempo.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Denne Ã¸velsen trener triceps.</li>
<li>Ã˜velsen kan ogsÃ¥ gjÃ¸res med tau.</li>
</ul>','exercise_created_datetime' => '2018-03-21 18:34:59','exercise_updated_datetime' => '2018-03-21 18:34:59','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '56','exercise_title' => 'Nedtrekk bredt grep','exercise_title_clean' => 'nedtrekk_bredt_grep','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '8','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '24','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Start med armene helt ut pÃ¥ toppen.</p>','exercise_guide' => '<p>Trekk stangen kontrollert mot brystet mens fokuset er pÃ¥ Ã¥ trekke albuen inn i siden. NÃ¥r stangen er ved brystet skal du presse noen sekuner fÃ¸r stangen bringes sakte tilbake til startposisjon. Tilbaketrekningen bÃ¸r vÃ¦re 2-4 sekunder. NÃ¥r stangen er pÃ¥ toppen skal armene vÃ¦re helt utstrakte og bevegelsen kan gjentas. SÃ¸rg for at skuldrene er trukket tilbake gjennom hele Ã¸velsen.</p>','exercise_important' => '<ul><li>
<p style="margin:4px 0px 6px 0px;padding:0;">Sitt nesten rett opp (og ikke lener vei tilbake som mange mennesker vil gjÃ¸re). Dette vil bidra til Ã¥ holde fokus pÃ¥ latissimus dorsi og ikke midten av ryggen.</p>
</li>
<li>
<p style="margin:4px 0px 6px 0px;padding:0;">Nedtrekk er ikke veldig komplisert, men vil du ofte se mange gjÃ¸re den feil. Hvis mÃ¥let ditt er styrke og stÃ¸rrelse for latissimus dorsi mÃ¥ Ã¸velsen utfÃ¸res med kontrollerte og lave vekter. Hold fokus pÃ¥ hvordan latissimus dorsi aktiveres gjennom hele bevegelsen.</p>
</li>
</ul>','exercise_created_datetime' => '2018-03-21 18:45:03','exercise_updated_datetime' => '2018-03-21 18:45:03','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '57','exercise_title' => 'Nedtrekk V-Bar','exercise_title_clean' => 'nedtrekk_v-bar','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '8','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '25','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Plasser lÃ¥rene under putene og strekk armene over hodet og ta tak i hÃ¥ndtakene. </p>','exercise_guide' => '<p>Trekk hÃ¥ndtaket mot Ã¸vre del av brystet. NÃ¥r hÃ¥ndtaket er ved brystet reverseres bevegeselen langsomt til utgangsposisjonen. Gjenta for Ã¸nsket antall repetisjoner.</p>','exercise_important' => '<ul><li>Ikke sving eller rykk i vektene i lÃ¸pet av Ã¸velsen. Kroppen bÃ¸r holde seg i ro under Ã¸velsen.</li>
</ul>','exercise_created_datetime' => '2018-03-21 18:55:24','exercise_updated_datetime' => '2018-03-21 18:59:32','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '58','exercise_title' => 'Liggende beinhev','exercise_title_clean' => 'liggende_beinhev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '26','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg deg pÃ¥ ryggen.</p>
<p>HaÂ  hendene pÃ¥ siden av kroppen din.</p>','exercise_guide' => '<p>LÃ¸ft opp beina dine, med knÃ¦rne litt bÃ¸yd. NÃ¥r beina er helt pÃ¥ toppen holder du en kort stund fÃ¸r du senker de igjen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Du kan gjÃ¸re denne Ã¸velsen pÃ¥ en yoga-matte.</li>
<li>Du kan legge pÃ¥ mer vekt ved Ã¥ holde en manual mellom fÃ¸ttende.</li>
</ul>','exercise_created_datetime' => '2018-03-23 16:22:42','exercise_updated_datetime' => '2018-03-23 16:22:42','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '59','exercise_title' => 'Liggende vekslende beinhev','exercise_title_clean' => 'liggende_vekslende_beinhev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '26','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg deg pÃ¥ ryggen.<br />Ha hendene pÃ¥ siden av kroppen din.</p>','exercise_guide' => '<p>LÃ¸ft opp det ene beinet ditt, med kneet litt bÃ¸yd. NÃ¥r beina er helt pÃ¥ toppen holder du en kort stund fÃ¸r du senker de igjen. <br />Gjenta sÃ¥ med det andre beinet</p>
<p>Gjenta hele prossedyren for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 16:31:40','exercise_updated_datetime' => '2018-03-23 16:31:40','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '60','exercise_title' => 'Beintrekk','exercise_title_clean' => 'beintrekk','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '3','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Sitt deg ned pÃ¥ en benk. <br />Hold deg fast med hendene pÃ¥ siden av benken.<br />Len deg litt tilbake, samtidig som du holder ryggen din rett.</p>','exercise_guide' => '<p>Dra inn fÃ¸ttene mot deg, samtidig som du bÃ¸yer knÃ¦rne dine. <br />Hold et lite Ã¸yeblikk og skyv sÃ¥ beina ut igjen. </p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 16:38:30','exercise_updated_datetime' => '2018-03-23 16:38:30','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '61','exercise_title' => 'Sittende twists','exercise_title_clean' => 'sittende_twists','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '27','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p>Finn en passende stÃ¸rrelse pÃ¥ en vekstkive, medisinball eller en kettlebell. <br />Sett deg pÃ¥ en treningsmatte.</p>','exercise_guide' => '<p>Enten roter overkroppen fra siden til siden. Dette kalles for russion twists.</p>
<p>Hvis du ikke Ã¸nsker dette kan du kun rotere armene.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 16:45:57','exercise_updated_datetime' => '2018-03-23 16:45:57','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '62','exercise_title' => 'Sit-ups','exercise_title_clean' => 'sit-ups','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '26','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg deg ned pÃ¥ en treningsmatte.</p>','exercise_guide' => '<p>LÃ¸ft deg opp med magemusklene til du er oppe. <br />Hold ryggen rett under Ã¸velsen.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '<ul><li>Ikke sving med kroppen.</li>
<li>Ikke dra deg fremover.</li>
</ul>','exercise_created_datetime' => '2018-03-23 16:54:44','exercise_updated_datetime' => '2018-03-23 16:54:44','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '63','exercise_title' => 'Hengende beinhev','exercise_title_clean' => 'hengende_beinhev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '5','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p><span lang="no" xml:lang="no"><span>Heng fra en stang med armene helt utstrakt. Beina skal vÃ¦re litt bak kroppen. <br /></span></span></p>','exercise_guide' => '<p><span lang="no" xml:lang="no"><span>LÃ¸ft beina til du fÃ¥r en 90 graders vinkel med beina.</span> <span>Pust ut nÃ¥r du utfÃ¸rer denne bevegelsen, og hold et Ã¸yeblikk fÃ¸r du gÃ¥r tilbake til utgangsstilling. <br /></span></span></p>
<p><span lang="no" xml:lang="no"><span>Repter for Ã¸nsket antall repitisjoner.</span></span></p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 16:59:51','exercise_updated_datetime' => '2018-03-23 16:59:51','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '64','exercise_title' => 'Cross-Body Crunch','exercise_title_clean' => 'cross-body_crunch','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '26','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p><span lang="no" xml:lang="no"><span>Finn en treningsmatte. Legg deg ned pÃ¥ den helt flat. Lag en bÃ¸y i knÃ¦rne pÃ¥ 60 grader.</span><br />Legg hendene lÃ¸st bak hodet. <span>Dette vil vÃ¦re din startposisjon.</span></span></p>','exercise_guide' => '<p>LÃ¸ft venstre bein og krÃ¸ll sammen kroppen med din hÃ¸yre overkropp. Senk sÃ¥ venstre bein og rett deg ut.<br />GjÃ¸r det samme med andre siden.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 17:17:15','exercise_updated_datetime' => '2018-03-23 17:25:06','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '65','exercise_title' => 'Omvendt skr&aring; crunches','exercise_title_clean' => 'omvendt_skra_crunches','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '6','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p><span lang="no" xml:lang="no">Juster en benk slik at den gÃ¥r pÃ¥ skrÃ¥ oppover. <br />Legg deg ned pÃ¥ benken med ryggen. <br />Hold deg fast i benken ved Ã¥ holde i toppen av benken. </span></p>
<p><span lang="no" xml:lang="no">Hold beina parallelt med gulvet med magemusklene. Beina skal vÃ¦re fullt utstrakt med en liten bÃ¸y pÃ¥ kneet. <br /></span></p>','exercise_guide' => '<p>Trekk beina mot deg og skyv de opp i lufen. Trekk de sÃ¥ mot deg og skyv de ut fra deg.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 17:29:09','exercise_updated_datetime' => '2018-03-23 17:29:09','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '66','exercise_title' => 'Rollout med hjul','exercise_title_clean' => 'rollout_med_hjul','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '28','exercise_type_id' => '2','exercise_level_id' => '2','exercise_preparation' => '<p>Sett deg pÃ¥ knÃ¦r. Hold hjulet med begge hendene. <br />Plasser hjulet pÃ¥ gulvet foran deg. <span lang="no" xml:lang="no"></span></p>
<p>Â </p>','exercise_guide' => '<p><span lang="no" xml:lang="no"><span>Rull sakte rett fremover, og strekk kroppen din i en rett stilling.</span><span> <br />GÃ¥ ned sÃ¥ langt du kan uten Ã¥ berÃ¸re gulvet med kroppen din.</span>Â </span></p>
<p><span lang="no" xml:lang="no">Rull deg sÃ¥ opp igjen.</span></p>
<p><span lang="no" xml:lang="no">Gjenta for Ã¸nsket antall repitisjoner.</span></p>
<p>Â </p>','exercise_important' => '<ul><li>Kontakt din PT om du har ryggproblemer for Ã¥ finne alternative Ã¸velser.</li>
</ul>','exercise_created_datetime' => '2018-03-23 17:37:16','exercise_updated_datetime' => '2018-03-23 17:37:16','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '67','exercise_title' => 'Ab crunches i kabel','exercise_title_clean' => 'ab_crunches_i_kabel','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '8','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still inn Ã¸nsket vekt i maskinen. <br />Fest pÃ¥ et tau. <br />Still deg med ryggen til maskinen og ta tak i tauet.</p>
<p>GÃ¥ ned slik at du sitter pÃ¥ knÃ¦r. Trekk ned vekten samtidig som du gÃ¥r ned i utgangs-stillingen.<br /><br /></p>','exercise_guide' => '<p>Beveg deg fremover slik at du kjenner magemusklene ta tak. <br />Trekk deg sÃ¥ kontrollert tilbake.</p>
<p>Gjenta for Ã¸nsket antall repitisjoner.</p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 17:59:36','exercise_updated_datetime' => '2018-03-23 17:59:36','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '68','exercise_title' => 'Flutter Kicks','exercise_title_clean' => 'flutter_kicks','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '22','exercise_muscle_group_id_sub' => '23','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '26','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Legg deg pÃ¥ magen eller ryggen.</p>','exercise_guide' => '<p><span lang="no" xml:lang="no">Hold beina rett og beveg ett bein opp. Senk det sÃ¥ ned igjen.<br />Beveg sÃ¥ det andre beinet opp og senk det sÃ¥ igjen.</span></p>
<p><span lang="no" xml:lang="no">Gjentaa for Ã¸nsket antall repitisjoner. </span><span lang="no" xml:lang="no"></span></p>','exercise_important' => '','exercise_created_datetime' => '2018-03-23 18:09:59','exercise_updated_datetime' => '2018-03-23 18:09:59','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL),
  array('exercise_id' => '69','exercise_title' => 'Rygghev','exercise_title_clean' => 'rygghev','exercise_user_id' => '1','exercise_language' => 'no','exercise_muscle_group_id_main' => '5','exercise_muscle_group_id_sub' => '9','exercise_muscle_part_of_id' => '0','exercise_equipment_id' => '29','exercise_type_id' => '2','exercise_level_id' => '1','exercise_preparation' => '<p>Still deg opp i rygghevstativet. <br />Ha eventuelt en vektskive liggende foran deg hvis du Ã¸nsker Ã¥ ha mer motstand i Ã¸velsen.</p>','exercise_guide' => '<p>GÃ¥ ned, mens du holder ryggen din rett. <br />Beveg deg sÃ¥ kontrollert opp igjen.<br />Ã˜velsen skal gi deg kontakt med nedredelen av ryggen din.</p>','exercise_important' => '<ul><li>Ha en rett rygg under Ã¸velsen.</li>
</ul>','exercise_created_datetime' => '2018-03-23 18:25:12','exercise_updated_datetime' => '2018-03-23 18:25:12','exercise_user_ip' => '81.166.225.197','exercise_uniqe_hits' => '0','exercise_uniqe_hits_ip_block' => NULL,'exercise_likes' => '0','exercise_dislikes' => '0','exercise_rating' => '0','exercise_rating_ip_block' => NULL,'exercise_number_of_comments' => '0','exercise_reported' => NULL,'exercise_reported_checked' => NULL,'exercise_reported_reason' => NULL)
);
		
		$datetime = date("Y-m-d H:i:s");
		foreach($stram_exercise_index as $v){
			
			$exercise_title = $v["exercise_title"];
			$exercise_title_clean = $v["exercise_title_clean"];
			$exercise_user_id = $v["exercise_user_id"];
			$exercise_language = $v["exercise_language"];
			$exercise_muscle_group_id_main = $v["exercise_muscle_group_id_main"];
			$exercise_muscle_group_id_sub = $v["exercise_muscle_group_id_sub"];
			$exercise_muscle_part_of_id = $v["exercise_muscle_part_of_id"];
			$exercise_equipment_id = $v["exercise_equipment_id"];
			if($exercise_equipment_id == ""){ $exercise_equipment_id = "0";	}
			$exercise_type_id = $v["exercise_type_id"];
			$exercise_level_id = $v["exercise_level_id"];
			$exercise_preparation = $v["exercise_preparation"];
			$exercise_guide = $v["exercise_guide"];
			$exercise_important = $v["exercise_important"];
		
			mysqli_query($link, "INSERT INTO $t_exercise_index
			(exercise_id, exercise_title, exercise_title_clean, exercise_user_id, exercise_language, exercise_muscle_group_id_main, 
			exercise_muscle_group_id_sub, exercise_muscle_part_of_id, exercise_equipment_id, exercise_type_id, exercise_level_id, exercise_preparation, exercise_guide, exercise_important, exercise_created_datetime, exercise_updated_datetime) 
			VALUES 
			(NULL, '$exercise_title', '$exercise_title_clean', '$exercise_user_id', '$exercise_language', '$exercise_muscle_group_id_main', 
			'$exercise_muscle_group_id_sub', '$exercise_muscle_part_of_id', '$exercise_equipment_id', '$exercise_type_id', '$exercise_level_id',
			'$exercise_preparation', '$exercise_guide', '$exercise_important', '$datetime', '$datetime')
			")
			or die(mysqli_error($link));


		}


	}
	echo"
	<!-- //exercises -->


";
?>