<?php
/**
*
* File: _admin/_inc/exercises/_liquibase/index.php
* Version 1.0.0
* Date 12:57 24.03.2021
* Copyright (c) 2021 Sindre Andre Ditlefsen
* License: http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/
/*- Access check ----------------------------------------------------------------------- */
if(!(isset($define_access_to_control_panel))){
	echo"<h1>Server error 403</h1>";
	die;
}

/*- Tables ---------------------------------------------------------------------------- */

$result = mysqli_query($link, "DROP TABLE IF EXISTS $t_exercise_index_videos") or die(mysqli_error($link)); 


echo"

	<!-- videos -->
	";
	$query = "SELECT * FROM $t_exercise_index_videos";
	$result = mysqli_query($link, $query);
	if($result !== FALSE){
		// Count rows
		$row_cnt = mysqli_num_rows($result);
		echo"
		<p>$t_exercise_index_videos: $row_cnt</p>
		";
	}
	else{
		mysqli_query($link, "CREATE TABLE $t_exercise_index_videos(
	  	 exercise_video_id INT NOT NULL AUTO_INCREMENT,
	 	  PRIMARY KEY(exercise_video_id), 
	  	   exercise_video_user_id INT,
	  	   exercise_video_exercise_id INT,
	  	   exercise_video_datetime DATETIME,
	  	   exercise_video_user_ip VARCHAR(250),
	  	   exercise_video_service_name VARCHAR(250),
	  	   exercise_video_service_id VARCHAR(250),
	  	   exercise_video_path VARCHAR(250),
	  	   exercise_video_file VARCHAR(250),
	  	   exercise_video_uniqe_hits INT,
	  	   exercise_video_uniqe_hits_ip_block TEXT)")
		   or die(mysqli_error());

$stram_exercise_index_videos = array(
  array('exercise_video_id' => '1','exercise_video_user_id' => '1','exercise_video_exercise_id' => '3','exercise_video_datetime' => '2018-02-18 12:52:09','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'kwG2ipFRgfo','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '2','exercise_video_user_id' => '1','exercise_video_exercise_id' => '4','exercise_video_datetime' => '2018-02-18 13:01:32','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'sAq_ocpRh_I','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '3','exercise_video_user_id' => '1','exercise_video_exercise_id' => '2','exercise_video_datetime' => '2018-02-18 20:09:09','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'vB5OHsJ3EME','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '4','exercise_video_user_id' => '1','exercise_video_exercise_id' => '5','exercise_video_datetime' => '2018-02-19 16:56:14','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '80369ZMnriU','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '6','exercise_video_user_id' => '1','exercise_video_exercise_id' => '7','exercise_video_datetime' => '2018-02-21 17:31:59','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'iBJls--mXAo','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '7','exercise_video_user_id' => '1','exercise_video_exercise_id' => '8','exercise_video_datetime' => '2018-02-21 17:46:18','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'EXj_Hq86ZGk','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '8','exercise_video_user_id' => '1','exercise_video_exercise_id' => '9','exercise_video_datetime' => '2018-03-10 17:20:03','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'cc6UVRS7PW4','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '9','exercise_video_user_id' => '1','exercise_video_exercise_id' => '10','exercise_video_datetime' => '2018-03-10 17:33:33','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'xhuzFDvo0Ik','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '10','exercise_video_user_id' => '1','exercise_video_exercise_id' => '11','exercise_video_datetime' => '2018-03-10 18:21:38','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'ep3scfNxL3A','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '11','exercise_video_user_id' => '1','exercise_video_exercise_id' => '12','exercise_video_datetime' => '2018-03-10 18:29:43','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '9G8aDAi24dA','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '12','exercise_video_user_id' => '1','exercise_video_exercise_id' => '13','exercise_video_datetime' => '2018-03-10 18:37:05','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'Iwe6AmxVf7o','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '13','exercise_video_user_id' => '1','exercise_video_exercise_id' => '14','exercise_video_datetime' => '2018-03-10 18:44:53','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'sLx7FNZzLeQ','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '14','exercise_video_user_id' => '1','exercise_video_exercise_id' => '15','exercise_video_datetime' => '2018-03-10 21:45:21','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'kRrftR4M0Hc','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '15','exercise_video_user_id' => '1','exercise_video_exercise_id' => '16','exercise_video_datetime' => '2018-03-10 21:51:44','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'sGVJbZd1dTM','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '16','exercise_video_user_id' => '1','exercise_video_exercise_id' => '17','exercise_video_datetime' => '2018-03-10 23:02:33','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'fMDRhzeYU1s','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '17','exercise_video_user_id' => '1','exercise_video_exercise_id' => '18','exercise_video_datetime' => '2018-03-10 23:13:16','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'veAQ73OJdwY','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '18','exercise_video_user_id' => '1','exercise_video_exercise_id' => '19','exercise_video_datetime' => '2018-03-11 09:04:02','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'fQS4YYb5TBg','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '19','exercise_video_user_id' => '1','exercise_video_exercise_id' => '20','exercise_video_datetime' => '2018-03-11 09:08:27','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'qwDUGD-NURc','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '20','exercise_video_user_id' => '1','exercise_video_exercise_id' => '21','exercise_video_datetime' => '2018-03-11 09:12:44','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'WamrGG-yQQc','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '21','exercise_video_user_id' => '1','exercise_video_exercise_id' => '22','exercise_video_datetime' => '2018-03-11 09:30:41','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'L5Kfveu51lc','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '22','exercise_video_user_id' => '1','exercise_video_exercise_id' => '23','exercise_video_datetime' => '2018-03-12 16:53:11','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'zC3nLlEvin4','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '23','exercise_video_user_id' => '1','exercise_video_exercise_id' => '24','exercise_video_datetime' => '2018-03-17 22:19:57','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'WizLaNKKKuE','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '24','exercise_video_user_id' => '1','exercise_video_exercise_id' => '25','exercise_video_datetime' => '2018-03-18 08:27:18','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'wQ1aFhHE0SE','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '25','exercise_video_user_id' => '1','exercise_video_exercise_id' => '26','exercise_video_datetime' => '2018-03-18 08:49:22','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'p8B0ecwM0gA','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '26','exercise_video_user_id' => '1','exercise_video_exercise_id' => '27','exercise_video_datetime' => '2018-03-18 09:04:48','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'sM6XUdt1rm4','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '27','exercise_video_user_id' => '1','exercise_video_exercise_id' => '28','exercise_video_datetime' => '2018-03-18 09:14:21','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'M1N804yWA-8','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '28','exercise_video_user_id' => '1','exercise_video_exercise_id' => '29','exercise_video_datetime' => '2018-03-18 09:30:33','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '1V4RXxLHNCY','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '29','exercise_video_user_id' => '1','exercise_video_exercise_id' => '30','exercise_video_datetime' => '2018-03-18 09:44:16','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '0xRvl4Qv3ZY','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '30','exercise_video_user_id' => '1','exercise_video_exercise_id' => '31','exercise_video_datetime' => '2018-03-18 15:06:52','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'GZpJ-GFU6-4','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '31','exercise_video_user_id' => '1','exercise_video_exercise_id' => '32','exercise_video_datetime' => '2018-03-18 15:58:32','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'eozdVDA78K0','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '32','exercise_video_user_id' => '1','exercise_video_exercise_id' => '33','exercise_video_datetime' => '2018-03-18 16:09:12','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'UoCYXLtYTqo','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '33','exercise_video_user_id' => '1','exercise_video_exercise_id' => '34','exercise_video_datetime' => '2018-03-18 16:17:00','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'I_9YzXFWfBs','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '34','exercise_video_user_id' => '1','exercise_video_exercise_id' => '35','exercise_video_datetime' => '2018-03-19 21:50:24','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'YyvSfVjQeL0','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '35','exercise_video_user_id' => '1','exercise_video_exercise_id' => '36','exercise_video_datetime' => '2018-03-20 16:37:01','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'Aq5uxXrXq7c','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '36','exercise_video_user_id' => '1','exercise_video_exercise_id' => '37','exercise_video_datetime' => '2018-03-20 16:48:30','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'd_KZxkY_0cM','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '37','exercise_video_user_id' => '1','exercise_video_exercise_id' => '38','exercise_video_datetime' => '2018-03-20 16:54:40','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 't2KWJeCGzc4','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '38','exercise_video_user_id' => '1','exercise_video_exercise_id' => '39','exercise_video_datetime' => '2018-03-20 17:03:22','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '-BG2-KADomM','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '39','exercise_video_user_id' => '1','exercise_video_exercise_id' => '40','exercise_video_datetime' => '2018-03-20 17:36:19','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '-4Z-KqH_mrw','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '40','exercise_video_user_id' => '1','exercise_video_exercise_id' => '41','exercise_video_datetime' => '2018-03-20 17:47:44','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'YbX7Wd8jQ-Q','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '41','exercise_video_user_id' => '1','exercise_video_exercise_id' => '42','exercise_video_datetime' => '2018-03-20 18:14:36','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'O4UiWEHB92U','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '42','exercise_video_user_id' => '1','exercise_video_exercise_id' => '43','exercise_video_datetime' => '2018-03-20 18:24:05','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'T2TFp7i6LGQ','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '43','exercise_video_user_id' => '1','exercise_video_exercise_id' => '44','exercise_video_datetime' => '2018-03-20 18:28:59','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'GY_Lghy-SSE','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '44','exercise_video_user_id' => '1','exercise_video_exercise_id' => '45','exercise_video_datetime' => '2018-03-20 21:29:48','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'qBKeaL9LAHk','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '45','exercise_video_user_id' => '1','exercise_video_exercise_id' => '46','exercise_video_datetime' => '2018-03-20 21:41:32','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'AV5PmZJIrrw','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '46','exercise_video_user_id' => '1','exercise_video_exercise_id' => '47','exercise_video_datetime' => '2018-03-21 17:08:45','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '9A5rFtR22mg','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '47','exercise_video_user_id' => '1','exercise_video_exercise_id' => '48','exercise_video_datetime' => '2018-03-21 17:20:35','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'ELOCsoDSmrg','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '48','exercise_video_user_id' => '1','exercise_video_exercise_id' => '49','exercise_video_datetime' => '2018-03-21 17:28:18','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'cJRVVxmytaM','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '49','exercise_video_user_id' => '1','exercise_video_exercise_id' => '50','exercise_video_datetime' => '2018-03-21 17:41:48','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'dL9ZzqtQI5c','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '50','exercise_video_user_id' => '1','exercise_video_exercise_id' => '51','exercise_video_datetime' => '2018-03-21 17:50:22','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'NXr4Fw8q60o','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '51','exercise_video_user_id' => '1','exercise_video_exercise_id' => '52','exercise_video_datetime' => '2018-03-21 18:10:28','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'bqmo9MrWeiI','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '52','exercise_video_user_id' => '1','exercise_video_exercise_id' => '53','exercise_video_datetime' => '2018-03-21 18:16:07','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'kyyP5l8noSY','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '53','exercise_video_user_id' => '1','exercise_video_exercise_id' => '54','exercise_video_datetime' => '2018-03-21 18:24:52','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'AjCCGN2tU3Q','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '54','exercise_video_user_id' => '1','exercise_video_exercise_id' => '55','exercise_video_datetime' => '2018-03-21 18:37:33','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'mRmIthbCSNI','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '55','exercise_video_user_id' => '1','exercise_video_exercise_id' => '56','exercise_video_datetime' => '2018-03-21 18:48:25','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'TJ9wo24eB3c','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '56','exercise_video_user_id' => '1','exercise_video_exercise_id' => '57','exercise_video_datetime' => '2018-03-21 18:59:32','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'EjIETxOawcg','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '57','exercise_video_user_id' => '1','exercise_video_exercise_id' => '58','exercise_video_datetime' => '2018-03-23 16:30:28','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'JB2oyawG9KI','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '58','exercise_video_user_id' => '1','exercise_video_exercise_id' => '59','exercise_video_datetime' => '2018-03-23 16:34:21','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'LhbEEzpO9sU','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '59','exercise_video_user_id' => '1','exercise_video_exercise_id' => '60','exercise_video_datetime' => '2018-03-23 16:42:19','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'GPBVNHl5cS8','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '60','exercise_video_user_id' => '1','exercise_video_exercise_id' => '61','exercise_video_datetime' => '2018-03-23 16:51:17','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'r8Ni_dhNvqc','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '61','exercise_video_user_id' => '1','exercise_video_exercise_id' => '62','exercise_video_datetime' => '2018-03-23 16:57:26','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => '1fbU_MkV7NE','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '62','exercise_video_user_id' => '1','exercise_video_exercise_id' => '63','exercise_video_datetime' => '2018-03-23 17:03:11','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'hdng3Nm1x_E','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '63','exercise_video_user_id' => '1','exercise_video_exercise_id' => '64','exercise_video_datetime' => '2018-03-23 17:20:17','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'cDIYH5rH0qU','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '64','exercise_video_user_id' => '1','exercise_video_exercise_id' => '65','exercise_video_datetime' => '2018-03-23 17:34:29','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'YcMj0EEadQo','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '65','exercise_video_user_id' => '1','exercise_video_exercise_id' => '66','exercise_video_datetime' => '2018-03-23 17:43:05','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'A3uK5TPzHq8','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '66','exercise_video_user_id' => '1','exercise_video_exercise_id' => '67','exercise_video_datetime' => '2018-03-23 18:07:16','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'NJQROeaBiVE','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '67','exercise_video_user_id' => '1','exercise_video_exercise_id' => '68','exercise_video_datetime' => '2018-03-23 18:12:58','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'ANVdMDaYRts','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => ''),
  array('exercise_video_id' => '68','exercise_video_user_id' => '1','exercise_video_exercise_id' => '69','exercise_video_datetime' => '2018-03-23 18:29:53','exercise_video_user_ip' => '81.166.225.197','exercise_video_service_name' => 'youtube','exercise_video_service_id' => 'Tcv0U7iylaI','exercise_video_path' => '','exercise_video_file' => '','exercise_video_uniqe_hits' => '0','exercise_video_uniqe_hits_ip_block' => '')
);


		foreach($stram_exercise_index_videos as $v){
			
			$exercise_video_user_id = $v["exercise_video_user_id"];
			$exercise_video_exercise_id = $v["exercise_video_exercise_id"];
			$exercise_video_datetime = $v["exercise_video_datetime"];
			$exercise_video_service_name = $v["exercise_video_service_name"];
			$exercise_video_service_id = $v["exercise_video_service_id"];
			$exercise_video_path = $v["exercise_video_path"];
			$exercise_video_file = $v["exercise_video_file"];
		
			mysqli_query($link, "INSERT INTO $t_exercise_index_videos
			(exercise_video_id, exercise_video_user_id, exercise_video_exercise_id, exercise_video_datetime, exercise_video_service_name, exercise_video_service_id, exercise_video_path, exercise_video_file) 
			VALUES 
			(NULL, '$exercise_video_user_id', '$exercise_video_exercise_id', '$exercise_video_datetime', '$exercise_video_service_name', '$exercise_video_service_id', '$exercise_video_path', '$exercise_video_file')
			")
			or die(mysqli_error($link));


		}



	}
	echo"
	<!-- //videos -->

";
?>